# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'customer_widget_design.ui'
#
# Created: Wed Sep 21 09:19:00 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_customerWidget(object):
    def setupUi(self, customerWidget):
        customerWidget.setObjectName(_fromUtf8("customerWidget"))
        customerWidget.resize(307, 240)
        customerWidget.setWindowTitle(QtGui.QApplication.translate("customerWidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout = QtGui.QVBoxLayout(customerWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.customerGroupBox = QtGui.QGroupBox(customerWidget)
        self.customerGroupBox.setTitle(QtGui.QApplication.translate("customerWidget", "Customer", None, QtGui.QApplication.UnicodeUTF8))
        self.customerGroupBox.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.customerGroupBox.setFlat(False)
        self.customerGroupBox.setCheckable(False)
        self.customerGroupBox.setObjectName(_fromUtf8("customerGroupBox"))
        self.formLayout = QtGui.QFormLayout(self.customerGroupBox)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.firstNameLabel = QtGui.QLabel(self.customerGroupBox)
        self.firstNameLabel.setText(QtGui.QApplication.translate("customerWidget", "First name", None, QtGui.QApplication.UnicodeUTF8))
        self.firstNameLabel.setObjectName(_fromUtf8("firstNameLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.firstNameLabel)
        self.firstNameLineEdit = ValidatingLineEdit(self.customerGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.firstNameLineEdit.sizePolicy().hasHeightForWidth())
        self.firstNameLineEdit.setSizePolicy(sizePolicy)
        self.firstNameLineEdit.setMinimumSize(QtCore.QSize(133, 20))
        self.firstNameLineEdit.setMaximumSize(QtCore.QSize(133, 20))
        self.firstNameLineEdit.setToolTip(QtGui.QApplication.translate("customerWidget", "Customer first name.", None, QtGui.QApplication.UnicodeUTF8))
        self.firstNameLineEdit.setStatusTip(QtGui.QApplication.translate("customerWidget", "Status test", None, QtGui.QApplication.UnicodeUTF8))
        self.firstNameLineEdit.setWhatsThis(QtGui.QApplication.translate("customerWidget", "The analog clock widget displays the current time.", None, QtGui.QApplication.UnicodeUTF8))
        self.firstNameLineEdit.setStyleSheet(_fromUtf8(""))
        self.firstNameLineEdit.setProperty("regexString", QtGui.QApplication.translate("customerWidget", "name", None, QtGui.QApplication.UnicodeUTF8))
        self.firstNameLineEdit.setObjectName(_fromUtf8("firstNameLineEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.firstNameLineEdit)
        self.lastNameLabel = QtGui.QLabel(self.customerGroupBox)
        self.lastNameLabel.setText(QtGui.QApplication.translate("customerWidget", "Last name", None, QtGui.QApplication.UnicodeUTF8))
        self.lastNameLabel.setObjectName(_fromUtf8("lastNameLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lastNameLabel)
        self.lastNameLineEdit = ValidatingLineEdit(self.customerGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lastNameLineEdit.sizePolicy().hasHeightForWidth())
        self.lastNameLineEdit.setSizePolicy(sizePolicy)
        self.lastNameLineEdit.setMinimumSize(QtCore.QSize(133, 20))
        self.lastNameLineEdit.setMaximumSize(QtCore.QSize(133, 20))
        self.lastNameLineEdit.setToolTip(QtGui.QApplication.translate("customerWidget", "Customer last name.", None, QtGui.QApplication.UnicodeUTF8))
        self.lastNameLineEdit.setWhatsThis(QtGui.QApplication.translate("customerWidget", "The analog clock widget displays the current time.", None, QtGui.QApplication.UnicodeUTF8))
        self.lastNameLineEdit.setStyleSheet(_fromUtf8(""))
        self.lastNameLineEdit.setProperty("regexString", QtGui.QApplication.translate("customerWidget", "name", None, QtGui.QApplication.UnicodeUTF8))
        self.lastNameLineEdit.setObjectName(_fromUtf8("lastNameLineEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lastNameLineEdit)
        self.houseNumberLabel = QtGui.QLabel(self.customerGroupBox)
        self.houseNumberLabel.setText(QtGui.QApplication.translate("customerWidget", "House number", None, QtGui.QApplication.UnicodeUTF8))
        self.houseNumberLabel.setObjectName(_fromUtf8("houseNumberLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.houseNumberLabel)
        self.houseNumberLineEdit = ValidatingLineEdit(self.customerGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.houseNumberLineEdit.sizePolicy().hasHeightForWidth())
        self.houseNumberLineEdit.setSizePolicy(sizePolicy)
        self.houseNumberLineEdit.setMinimumSize(QtCore.QSize(51, 20))
        self.houseNumberLineEdit.setMaximumSize(QtCore.QSize(51, 20))
        self.houseNumberLineEdit.setToolTip(QtGui.QApplication.translate("customerWidget", "Customer house number.", None, QtGui.QApplication.UnicodeUTF8))
        self.houseNumberLineEdit.setWhatsThis(QtGui.QApplication.translate("customerWidget", "The analog clock widget displays the current time.", None, QtGui.QApplication.UnicodeUTF8))
        self.houseNumberLineEdit.setProperty("regexString", QtGui.QApplication.translate("customerWidget", "houseNumber", None, QtGui.QApplication.UnicodeUTF8))
        self.houseNumberLineEdit.setObjectName(_fromUtf8("houseNumberLineEdit"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.houseNumberLineEdit)
        self.streetLabel = QtGui.QLabel(self.customerGroupBox)
        self.streetLabel.setText(QtGui.QApplication.translate("customerWidget", "Street", None, QtGui.QApplication.UnicodeUTF8))
        self.streetLabel.setObjectName(_fromUtf8("streetLabel"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.streetLabel)
        self.streetLineEdit = ValidatingLineEdit(self.customerGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.streetLineEdit.sizePolicy().hasHeightForWidth())
        self.streetLineEdit.setSizePolicy(sizePolicy)
        self.streetLineEdit.setMinimumSize(QtCore.QSize(133, 20))
        self.streetLineEdit.setMaximumSize(QtCore.QSize(133, 20))
        self.streetLineEdit.setToolTip(QtGui.QApplication.translate("customerWidget", "Customer address street.", None, QtGui.QApplication.UnicodeUTF8))
        self.streetLineEdit.setWhatsThis(QtGui.QApplication.translate("customerWidget", "The analog clock widget displays the current time.", None, QtGui.QApplication.UnicodeUTF8))
        self.streetLineEdit.setProperty("regexString", QtGui.QApplication.translate("customerWidget", "street", None, QtGui.QApplication.UnicodeUTF8))
        self.streetLineEdit.setObjectName(_fromUtf8("streetLineEdit"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.streetLineEdit)
        self.townLabel = QtGui.QLabel(self.customerGroupBox)
        self.townLabel.setText(QtGui.QApplication.translate("customerWidget", "Town", None, QtGui.QApplication.UnicodeUTF8))
        self.townLabel.setObjectName(_fromUtf8("townLabel"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.townLabel)
        self.townLineEdit = ValidatingLineEdit(self.customerGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.townLineEdit.sizePolicy().hasHeightForWidth())
        self.townLineEdit.setSizePolicy(sizePolicy)
        self.townLineEdit.setMinimumSize(QtCore.QSize(101, 20))
        self.townLineEdit.setMaximumSize(QtCore.QSize(101, 20))
        self.townLineEdit.setToolTip(QtGui.QApplication.translate("customerWidget", "Customer address town.", None, QtGui.QApplication.UnicodeUTF8))
        self.townLineEdit.setWhatsThis(QtGui.QApplication.translate("customerWidget", "The analog clock widget displays the current time.", None, QtGui.QApplication.UnicodeUTF8))
        self.townLineEdit.setProperty("regexString", QtGui.QApplication.translate("customerWidget", "town", None, QtGui.QApplication.UnicodeUTF8))
        self.townLineEdit.setObjectName(_fromUtf8("townLineEdit"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.townLineEdit)
        self.postcodeLabel = QtGui.QLabel(self.customerGroupBox)
        self.postcodeLabel.setText(QtGui.QApplication.translate("customerWidget", "Postcode", None, QtGui.QApplication.UnicodeUTF8))
        self.postcodeLabel.setObjectName(_fromUtf8("postcodeLabel"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.postcodeLabel)
        self.postcodeLineEdit = ValidatingLineEdit(self.customerGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.postcodeLineEdit.sizePolicy().hasHeightForWidth())
        self.postcodeLineEdit.setSizePolicy(sizePolicy)
        self.postcodeLineEdit.setMinimumSize(QtCore.QSize(51, 20))
        self.postcodeLineEdit.setMaximumSize(QtCore.QSize(71, 20))
        self.postcodeLineEdit.setToolTip(QtGui.QApplication.translate("customerWidget", "Customer address postcode.", None, QtGui.QApplication.UnicodeUTF8))
        self.postcodeLineEdit.setWhatsThis(QtGui.QApplication.translate("customerWidget", "The analog clock widget displays the current time.", None, QtGui.QApplication.UnicodeUTF8))
        self.postcodeLineEdit.setProperty("regexString", QtGui.QApplication.translate("customerWidget", "postcode", None, QtGui.QApplication.UnicodeUTF8))
        self.postcodeLineEdit.setObjectName(_fromUtf8("postcodeLineEdit"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.postcodeLineEdit)
        self.vehicleRegistrationLabel = QtGui.QLabel(self.customerGroupBox)
        self.vehicleRegistrationLabel.setText(QtGui.QApplication.translate("customerWidget", "Vehicle Registration", None, QtGui.QApplication.UnicodeUTF8))
        self.vehicleRegistrationLabel.setObjectName(_fromUtf8("vehicleRegistrationLabel"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.vehicleRegistrationLabel)
        self.customerRegistrationLineEdit = ValidatingLineEdit(self.customerGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.customerRegistrationLineEdit.sizePolicy().hasHeightForWidth())
        self.customerRegistrationLineEdit.setSizePolicy(sizePolicy)
        self.customerRegistrationLineEdit.setMinimumSize(QtCore.QSize(71, 20))
        self.customerRegistrationLineEdit.setMaximumSize(QtCore.QSize(71, 20))
        self.customerRegistrationLineEdit.setToolTip(QtGui.QApplication.translate("customerWidget", "Customer\'s vehicle registration number.", None, QtGui.QApplication.UnicodeUTF8))
        self.customerRegistrationLineEdit.setWhatsThis(QtGui.QApplication.translate("customerWidget", "The analog clock widget displays the current time.", None, QtGui.QApplication.UnicodeUTF8))
        self.customerRegistrationLineEdit.setProperty("regexString", QtGui.QApplication.translate("customerWidget", "post2001Reg", None, QtGui.QApplication.UnicodeUTF8))
        self.customerRegistrationLineEdit.setObjectName(_fromUtf8("customerRegistrationLineEdit"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.customerRegistrationLineEdit)
        self.verticalLayout.addWidget(self.customerGroupBox)

        self.retranslateUi(customerWidget)
        QtCore.QMetaObject.connectSlotsByName(customerWidget)

    def retranslateUi(self, customerWidget):
        pass

from custom_widgets.validatingLineEdit import ValidatingLineEdit
