# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'customer_widget_design.ui'
#
# Created: Mon Sep 19 11:18:14 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(468, 535)
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem = QtGui.QSpacerItem(20, 50, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem1 = QtGui.QSpacerItem(128, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.customerGroupBox = QtGui.QGroupBox(Form)
        self.customerGroupBox.setTitle(QtGui.QApplication.translate("Form", "Customer", None, QtGui.QApplication.UnicodeUTF8))
        self.customerGroupBox.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.customerGroupBox.setObjectName(_fromUtf8("customerGroupBox"))
        self.formLayout = QtGui.QFormLayout(self.customerGroupBox)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.firstNameLabel = QtGui.QLabel(self.customerGroupBox)
        self.firstNameLabel.setText(QtGui.QApplication.translate("Form", "First name", None, QtGui.QApplication.UnicodeUTF8))
        self.firstNameLabel.setObjectName(_fromUtf8("firstNameLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.firstNameLabel)
        self.firstNameLineEdit = ValidatingLineEdit(self.customerGroupBox)
        self.firstNameLineEdit.setMinimumSize(QtCore.QSize(133, 20))
        self.firstNameLineEdit.setMaximumSize(QtCore.QSize(133, 20))
        self.firstNameLineEdit.setToolTip(QtGui.QApplication.translate("Form", "Customer first name.", None, QtGui.QApplication.UnicodeUTF8))
        self.firstNameLineEdit.setStatusTip(QtGui.QApplication.translate("Form", "Status test", None, QtGui.QApplication.UnicodeUTF8))
        self.firstNameLineEdit.setWhatsThis(QtGui.QApplication.translate("Form", "The analog clock widget displays the current time.", None, QtGui.QApplication.UnicodeUTF8))
        self.firstNameLineEdit.setStyleSheet(_fromUtf8("QLineEdit {background-color: red;}"))
        self.firstNameLineEdit.setProperty("regexString", QtGui.QApplication.translate("Form", "name", None, QtGui.QApplication.UnicodeUTF8))
        self.firstNameLineEdit.setObjectName(_fromUtf8("firstNameLineEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.firstNameLineEdit)
        self.lastNameLabel = QtGui.QLabel(self.customerGroupBox)
        self.lastNameLabel.setText(QtGui.QApplication.translate("Form", "Last name", None, QtGui.QApplication.UnicodeUTF8))
        self.lastNameLabel.setObjectName(_fromUtf8("lastNameLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lastNameLabel)
        self.lastNameLineEdit = ValidatingLineEdit(self.customerGroupBox)
        self.lastNameLineEdit.setMinimumSize(QtCore.QSize(133, 20))
        self.lastNameLineEdit.setMaximumSize(QtCore.QSize(133, 20))
        self.lastNameLineEdit.setToolTip(QtGui.QApplication.translate("Form", "Customer last name.", None, QtGui.QApplication.UnicodeUTF8))
        self.lastNameLineEdit.setWhatsThis(QtGui.QApplication.translate("Form", "The analog clock widget displays the current time.", None, QtGui.QApplication.UnicodeUTF8))
        self.lastNameLineEdit.setStyleSheet(_fromUtf8("QLineEdit {background-color: red;}"))
        self.lastNameLineEdit.setProperty("regexString", QtGui.QApplication.translate("Form", "name", None, QtGui.QApplication.UnicodeUTF8))
        self.lastNameLineEdit.setObjectName(_fromUtf8("lastNameLineEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lastNameLineEdit)
        self.houseNumberLabel = QtGui.QLabel(self.customerGroupBox)
        self.houseNumberLabel.setText(QtGui.QApplication.translate("Form", "House number", None, QtGui.QApplication.UnicodeUTF8))
        self.houseNumberLabel.setObjectName(_fromUtf8("houseNumberLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.houseNumberLabel)
        self.houseNumberLineEdit = ValidatingLineEdit(self.customerGroupBox)
        self.houseNumberLineEdit.setMinimumSize(QtCore.QSize(51, 20))
        self.houseNumberLineEdit.setMaximumSize(QtCore.QSize(51, 20))
        self.houseNumberLineEdit.setToolTip(QtGui.QApplication.translate("Form", "Customer house number.", None, QtGui.QApplication.UnicodeUTF8))
        self.houseNumberLineEdit.setWhatsThis(QtGui.QApplication.translate("Form", "The analog clock widget displays the current time.", None, QtGui.QApplication.UnicodeUTF8))
        self.houseNumberLineEdit.setStyleSheet(_fromUtf8("QLineEdit {background-color: red;}"))
        self.houseNumberLineEdit.setProperty("regexString", QtGui.QApplication.translate("Form", "houseNumber", None, QtGui.QApplication.UnicodeUTF8))
        self.houseNumberLineEdit.setObjectName(_fromUtf8("houseNumberLineEdit"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.houseNumberLineEdit)
        self.streetLabel = QtGui.QLabel(self.customerGroupBox)
        self.streetLabel.setText(QtGui.QApplication.translate("Form", "Street", None, QtGui.QApplication.UnicodeUTF8))
        self.streetLabel.setObjectName(_fromUtf8("streetLabel"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.streetLabel)
        self.streetLineEdit = ValidatingLineEdit(self.customerGroupBox)
        self.streetLineEdit.setMinimumSize(QtCore.QSize(133, 20))
        self.streetLineEdit.setMaximumSize(QtCore.QSize(133, 20))
        self.streetLineEdit.setToolTip(QtGui.QApplication.translate("Form", "Customer address street.", None, QtGui.QApplication.UnicodeUTF8))
        self.streetLineEdit.setWhatsThis(QtGui.QApplication.translate("Form", "The analog clock widget displays the current time.", None, QtGui.QApplication.UnicodeUTF8))
        self.streetLineEdit.setStyleSheet(_fromUtf8("QLineEdit {background-color: red;}"))
        self.streetLineEdit.setProperty("regexString", QtGui.QApplication.translate("Form", "street", None, QtGui.QApplication.UnicodeUTF8))
        self.streetLineEdit.setObjectName(_fromUtf8("streetLineEdit"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.streetLineEdit)
        self.townLabel = QtGui.QLabel(self.customerGroupBox)
        self.townLabel.setText(QtGui.QApplication.translate("Form", "Town", None, QtGui.QApplication.UnicodeUTF8))
        self.townLabel.setObjectName(_fromUtf8("townLabel"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.townLabel)
        self.townLineEdit = ValidatingLineEdit(self.customerGroupBox)
        self.townLineEdit.setMinimumSize(QtCore.QSize(101, 20))
        self.townLineEdit.setMaximumSize(QtCore.QSize(101, 20))
        self.townLineEdit.setToolTip(QtGui.QApplication.translate("Form", "Customer address town.", None, QtGui.QApplication.UnicodeUTF8))
        self.townLineEdit.setWhatsThis(QtGui.QApplication.translate("Form", "The analog clock widget displays the current time.", None, QtGui.QApplication.UnicodeUTF8))
        self.townLineEdit.setStyleSheet(_fromUtf8("QLineEdit {background-color: red;}"))
        self.townLineEdit.setProperty("regexString", QtGui.QApplication.translate("Form", "town", None, QtGui.QApplication.UnicodeUTF8))
        self.townLineEdit.setObjectName(_fromUtf8("townLineEdit"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.townLineEdit)
        self.postcodeLabel = QtGui.QLabel(self.customerGroupBox)
        self.postcodeLabel.setText(QtGui.QApplication.translate("Form", "Postcode", None, QtGui.QApplication.UnicodeUTF8))
        self.postcodeLabel.setObjectName(_fromUtf8("postcodeLabel"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.postcodeLabel)
        self.postcodeLineEdit = ValidatingLineEdit(self.customerGroupBox)
        self.postcodeLineEdit.setMinimumSize(QtCore.QSize(51, 20))
        self.postcodeLineEdit.setMaximumSize(QtCore.QSize(71, 20))
        self.postcodeLineEdit.setToolTip(QtGui.QApplication.translate("Form", "Customer address postcode.", None, QtGui.QApplication.UnicodeUTF8))
        self.postcodeLineEdit.setWhatsThis(QtGui.QApplication.translate("Form", "The analog clock widget displays the current time.", None, QtGui.QApplication.UnicodeUTF8))
        self.postcodeLineEdit.setStyleSheet(_fromUtf8("QLineEdit {background-color: red;}"))
        self.postcodeLineEdit.setProperty("regexString", QtGui.QApplication.translate("Form", "postcode", None, QtGui.QApplication.UnicodeUTF8))
        self.postcodeLineEdit.setObjectName(_fromUtf8("postcodeLineEdit"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.postcodeLineEdit)
        self.vehicleRegistrationLabel = QtGui.QLabel(self.customerGroupBox)
        self.vehicleRegistrationLabel.setText(QtGui.QApplication.translate("Form", "Vehicle Registration", None, QtGui.QApplication.UnicodeUTF8))
        self.vehicleRegistrationLabel.setObjectName(_fromUtf8("vehicleRegistrationLabel"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.vehicleRegistrationLabel)
        self.customerRegistrationLineEdit = ValidatingLineEdit(self.customerGroupBox)
        self.customerRegistrationLineEdit.setMinimumSize(QtCore.QSize(71, 20))
        self.customerRegistrationLineEdit.setMaximumSize(QtCore.QSize(71, 20))
        self.customerRegistrationLineEdit.setToolTip(QtGui.QApplication.translate("Form", "Customer\'s vehicle registration number.", None, QtGui.QApplication.UnicodeUTF8))
        self.customerRegistrationLineEdit.setWhatsThis(QtGui.QApplication.translate("Form", "The analog clock widget displays the current time.", None, QtGui.QApplication.UnicodeUTF8))
        self.customerRegistrationLineEdit.setStyleSheet(_fromUtf8("QLineEdit {background-color: red;}"))
        self.customerRegistrationLineEdit.setProperty("regexString", QtGui.QApplication.translate("Form", "post2001Reg", None, QtGui.QApplication.UnicodeUTF8))
        self.customerRegistrationLineEdit.setObjectName(_fromUtf8("customerRegistrationLineEdit"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.customerRegistrationLineEdit)
        self.horizontalLayout.addWidget(self.customerGroupBox)
        spacerItem2 = QtGui.QSpacerItem(128, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.textBrowser = QtGui.QTextBrowser(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setFrameShape(QtGui.QFrame.StyledPanel)
        self.textBrowser.setFrameShadow(QtGui.QFrame.Sunken)
        self.textBrowser.setLineWidth(1)
        self.textBrowser.setAutoFormatting(QtGui.QTextEdit.AutoBulletList)
        self.textBrowser.setHtml(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Welcome to the new ticket creation screen!</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.verticalLayout.addWidget(self.textBrowser)
        spacerItem3 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        pass

from custom_widgets.validatingLineEdit import ValidatingLineEdit
