# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home_widget_design.ui'
#
# Created: Thu Sep 15 16:49:22 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(595, 449)
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "Tickets", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.newTicketButton = QtGui.QPushButton(self.groupBox)
        self.newTicketButton.setMinimumSize(QtCore.QSize(80, 26))
        self.newTicketButton.setText(QtGui.QApplication.translate("Form", "New Ticket", None, QtGui.QApplication.UnicodeUTF8))
        self.newTicketButton.setObjectName(_fromUtf8("newTicketButton"))
        self.verticalLayout.addWidget(self.newTicketButton)
        self.verifyTicketButton = QtGui.QPushButton(self.groupBox)
        self.verifyTicketButton.setMinimumSize(QtCore.QSize(80, 26))
        self.verifyTicketButton.setText(QtGui.QApplication.translate("Form", "Verify Ticket", None, QtGui.QApplication.UnicodeUTF8))
        self.verifyTicketButton.setObjectName(_fromUtf8("verifyTicketButton"))
        self.verticalLayout.addWidget(self.verifyTicketButton)
        self.searchTicketsButton = QtGui.QPushButton(self.groupBox)
        self.searchTicketsButton.setMinimumSize(QtCore.QSize(101, 26))
        self.searchTicketsButton.setText(QtGui.QApplication.translate("Form", "Search Tickets", None, QtGui.QApplication.UnicodeUTF8))
        self.searchTicketsButton.setObjectName(_fromUtf8("searchTicketsButton"))
        self.verticalLayout.addWidget(self.searchTicketsButton)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(Form)
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Form", "Materials", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.pushButton_4 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_4.setMinimumSize(QtCore.QSize(80, 26))
        self.pushButton_4.setText(QtGui.QApplication.translate("Form", "New Material", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_9 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_9.setMinimumSize(QtCore.QSize(80, 26))
        self.pushButton_9.setText(QtGui.QApplication.translate("Form", "Update Material", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.verticalLayout_2.addWidget(self.pushButton_9)
        self.pushButton_10 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_10.setMinimumSize(QtCore.QSize(80, 26))
        self.pushButton_10.setText(QtGui.QApplication.translate("Form", "View Materials", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.verticalLayout_2.addWidget(self.pushButton_10)
        self.gridLayout.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(Form)
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Form", "Money Pool", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.pushButton_5 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_5.setMinimumSize(QtCore.QSize(80, 26))
        self.pushButton_5.setText(QtGui.QApplication.translate("Form", "Add Money", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.verticalLayout_3.addWidget(self.pushButton_5)
        self.pushButton_11 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_11.setMinimumSize(QtCore.QSize(80, 26))
        self.pushButton_11.setText(QtGui.QApplication.translate("Form", "View Pool", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.verticalLayout_3.addWidget(self.pushButton_11)
        self.gridLayout.addWidget(self.groupBox_3, 0, 2, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(Form)
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Form", "Invoices", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.pushButton_12 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_12.setMinimumSize(QtCore.QSize(80, 26))
        self.pushButton_12.setText(QtGui.QApplication.translate("Form", "New Invoice", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.verticalLayout_6.addWidget(self.pushButton_12)
        self.gridLayout.addWidget(self.groupBox_4, 1, 0, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(Form)
        self.groupBox_5.setTitle(QtGui.QApplication.translate("Form", "Statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.pushButton_7 = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_7.setMinimumSize(QtCore.QSize(80, 26))
        self.pushButton_7.setText(QtGui.QApplication.translate("Form", "Summary", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.verticalLayout_4.addWidget(self.pushButton_7)
        self.pushButton_13 = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_13.setMinimumSize(QtCore.QSize(80, 26))
        self.pushButton_13.setText(QtGui.QApplication.translate("Form", "Total Tickets", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.verticalLayout_4.addWidget(self.pushButton_13)
        self.gridLayout.addWidget(self.groupBox_5, 1, 1, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(Form)
        self.groupBox_6.setTitle(QtGui.QApplication.translate("Form", "Annual Returns", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.pushButton_8 = QtGui.QPushButton(self.groupBox_6)
        self.pushButton_8.setMinimumSize(QtCore.QSize(80, 26))
        self.pushButton_8.setText(QtGui.QApplication.translate("Form", "New Record", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.verticalLayout_5.addWidget(self.pushButton_8)
        self.pushButton_14 = QtGui.QPushButton(self.groupBox_6)
        self.pushButton_14.setMinimumSize(QtCore.QSize(80, 26))
        self.pushButton_14.setText(QtGui.QApplication.translate("Form", "View Records", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.verticalLayout_5.addWidget(self.pushButton_14)
        self.gridLayout.addWidget(self.groupBox_6, 1, 2, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        pass

