# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'material_widget_design.ui'
#
# Created: Thu Sep 29 11:38:33 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_materialWidget(object):
    def setupUi(self, materialWidget):
        materialWidget.setObjectName(_fromUtf8("materialWidget"))
        materialWidget.resize(450, 249)
        materialWidget.setWindowTitle(QtGui.QApplication.translate("materialWidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(materialWidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.materialTable = QtGui.QTableWidget(materialWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.materialTable.sizePolicy().hasHeightForWidth())
        self.materialTable.setSizePolicy(sizePolicy)
        self.materialTable.setMaximumSize(QtCore.QSize(400, 400))
        self.materialTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.materialTable.setDragDropOverwriteMode(False)
        self.materialTable.setAlternatingRowColors(True)
        self.materialTable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.materialTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.materialTable.setObjectName(_fromUtf8("materialTable"))
        self.materialTable.setColumnCount(2)
        self.materialTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("materialWidget", "Material", None, QtGui.QApplication.UnicodeUTF8))
        self.materialTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("materialWidget", "PPU", None, QtGui.QApplication.UnicodeUTF8))
        self.materialTable.setHorizontalHeaderItem(1, item)
        self.materialTable.horizontalHeader().setCascadingSectionResizes(True)
        self.materialTable.horizontalHeader().setDefaultSectionSize(80)
        self.materialTable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.materialTable)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton = QtGui.QPushButton(materialWidget)
        self.pushButton.setText(QtGui.QApplication.translate("materialWidget", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtGui.QPushButton(materialWidget)
        self.pushButton_2.setText(QtGui.QApplication.translate("materialWidget", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.vehicleBox = QtGui.QGroupBox(materialWidget)
        self.vehicleBox.setEnabled(False)
        self.vehicleBox.setTitle(QtGui.QApplication.translate("materialWidget", "Vehicle", None, QtGui.QApplication.UnicodeUTF8))
        self.vehicleBox.setCheckable(False)
        self.vehicleBox.setObjectName(_fromUtf8("vehicleBox"))
        self.gridLayout = QtGui.QGridLayout(self.vehicleBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.makeLabel = QtGui.QLabel(self.vehicleBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.makeLabel.sizePolicy().hasHeightForWidth())
        self.makeLabel.setSizePolicy(sizePolicy)
        self.makeLabel.setMinimumSize(QtCore.QSize(32, 16))
        self.makeLabel.setMaximumSize(QtCore.QSize(32, 16))
        self.makeLabel.setText(QtGui.QApplication.translate("materialWidget", "Make", None, QtGui.QApplication.UnicodeUTF8))
        self.makeLabel.setObjectName(_fromUtf8("makeLabel"))
        self.gridLayout.addWidget(self.makeLabel, 0, 0, 1, 1)
        self.makeEdit = ValidatingLineEdit(self.vehicleBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.makeEdit.sizePolicy().hasHeightForWidth())
        self.makeEdit.setSizePolicy(sizePolicy)
        self.makeEdit.setMinimumSize(QtCore.QSize(161, 25))
        self.makeEdit.setMaximumSize(QtCore.QSize(161, 25))
        self.makeEdit.setToolTip(QtGui.QApplication.translate("materialWidget", "Enter vehicle make.", None, QtGui.QApplication.UnicodeUTF8))
        self.makeEdit.setWhatsThis(QtGui.QApplication.translate("materialWidget", "The analog clock widget displays the current time.", None, QtGui.QApplication.UnicodeUTF8))
        self.makeEdit.setStyleSheet(_fromUtf8("QLineEdit {background-color: red;}"))
        self.makeEdit.setProperty("regexString", QtGui.QApplication.translate("materialWidget", "street", None, QtGui.QApplication.UnicodeUTF8))
        self.makeEdit.setObjectName(_fromUtf8("makeEdit"))
        self.gridLayout.addWidget(self.makeEdit, 0, 1, 1, 2)
        self.modelLabel = QtGui.QLabel(self.vehicleBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modelLabel.sizePolicy().hasHeightForWidth())
        self.modelLabel.setSizePolicy(sizePolicy)
        self.modelLabel.setMinimumSize(QtCore.QSize(36, 16))
        self.modelLabel.setMaximumSize(QtCore.QSize(36, 16))
        self.modelLabel.setText(QtGui.QApplication.translate("materialWidget", "Model", None, QtGui.QApplication.UnicodeUTF8))
        self.modelLabel.setObjectName(_fromUtf8("modelLabel"))
        self.gridLayout.addWidget(self.modelLabel, 1, 0, 1, 1)
        self.modelEdit = ValidatingLineEdit(self.vehicleBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modelEdit.sizePolicy().hasHeightForWidth())
        self.modelEdit.setSizePolicy(sizePolicy)
        self.modelEdit.setMinimumSize(QtCore.QSize(161, 25))
        self.modelEdit.setMaximumSize(QtCore.QSize(161, 25))
        self.modelEdit.setToolTip(QtGui.QApplication.translate("materialWidget", "Enter vehicle model.", None, QtGui.QApplication.UnicodeUTF8))
        self.modelEdit.setWhatsThis(QtGui.QApplication.translate("materialWidget", "The analog clock widget displays the current time.", None, QtGui.QApplication.UnicodeUTF8))
        self.modelEdit.setStyleSheet(_fromUtf8(""))
        self.modelEdit.setProperty("regexString", QtGui.QApplication.translate("materialWidget", "model", None, QtGui.QApplication.UnicodeUTF8))
        self.modelEdit.setObjectName(_fromUtf8("modelEdit"))
        self.gridLayout.addWidget(self.modelEdit, 1, 1, 1, 2)
        self.colourLabel = QtGui.QLabel(self.vehicleBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colourLabel.sizePolicy().hasHeightForWidth())
        self.colourLabel.setSizePolicy(sizePolicy)
        self.colourLabel.setMinimumSize(QtCore.QSize(39, 16))
        self.colourLabel.setMaximumSize(QtCore.QSize(39, 16))
        self.colourLabel.setText(QtGui.QApplication.translate("materialWidget", "Colour", None, QtGui.QApplication.UnicodeUTF8))
        self.colourLabel.setObjectName(_fromUtf8("colourLabel"))
        self.gridLayout.addWidget(self.colourLabel, 2, 0, 1, 1)
        self.colourCombobox = QtGui.QComboBox(self.vehicleBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colourCombobox.sizePolicy().hasHeightForWidth())
        self.colourCombobox.setSizePolicy(sizePolicy)
        self.colourCombobox.setMinimumSize(QtCore.QSize(121, 25))
        self.colourCombobox.setMaximumSize(QtCore.QSize(121, 25))
        self.colourCombobox.setToolTip(QtGui.QApplication.translate("materialWidget", "Select vehicle colour.", None, QtGui.QApplication.UnicodeUTF8))
        self.colourCombobox.setObjectName(_fromUtf8("colourCombobox"))
        self.colourCombobox.addItem(_fromUtf8(""))
        self.colourCombobox.setItemText(0, QtGui.QApplication.translate("materialWidget", "Black", None, QtGui.QApplication.UnicodeUTF8))
        self.colourCombobox.addItem(_fromUtf8(""))
        self.colourCombobox.setItemText(1, QtGui.QApplication.translate("materialWidget", "Blue", None, QtGui.QApplication.UnicodeUTF8))
        self.colourCombobox.addItem(_fromUtf8(""))
        self.colourCombobox.setItemText(2, QtGui.QApplication.translate("materialWidget", "Brown", None, QtGui.QApplication.UnicodeUTF8))
        self.colourCombobox.addItem(_fromUtf8(""))
        self.colourCombobox.setItemText(3, QtGui.QApplication.translate("materialWidget", "Green", None, QtGui.QApplication.UnicodeUTF8))
        self.colourCombobox.addItem(_fromUtf8(""))
        self.colourCombobox.setItemText(4, QtGui.QApplication.translate("materialWidget", "Grey", None, QtGui.QApplication.UnicodeUTF8))
        self.colourCombobox.addItem(_fromUtf8(""))
        self.colourCombobox.setItemText(5, QtGui.QApplication.translate("materialWidget", "Orange", None, QtGui.QApplication.UnicodeUTF8))
        self.colourCombobox.addItem(_fromUtf8(""))
        self.colourCombobox.setItemText(6, QtGui.QApplication.translate("materialWidget", "Pink", None, QtGui.QApplication.UnicodeUTF8))
        self.colourCombobox.addItem(_fromUtf8(""))
        self.colourCombobox.setItemText(7, QtGui.QApplication.translate("materialWidget", "Purple", None, QtGui.QApplication.UnicodeUTF8))
        self.colourCombobox.addItem(_fromUtf8(""))
        self.colourCombobox.setItemText(8, QtGui.QApplication.translate("materialWidget", "Red", None, QtGui.QApplication.UnicodeUTF8))
        self.colourCombobox.addItem(_fromUtf8(""))
        self.colourCombobox.setItemText(9, QtGui.QApplication.translate("materialWidget", "White", None, QtGui.QApplication.UnicodeUTF8))
        self.colourCombobox.addItem(_fromUtf8(""))
        self.colourCombobox.setItemText(10, QtGui.QApplication.translate("materialWidget", "Yellow", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLayout.addWidget(self.colourCombobox, 2, 1, 1, 2)
        self.vehicleRegistrationLabel_2 = QtGui.QLabel(self.vehicleBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vehicleRegistrationLabel_2.sizePolicy().hasHeightForWidth())
        self.vehicleRegistrationLabel_2.setSizePolicy(sizePolicy)
        self.vehicleRegistrationLabel_2.setMinimumSize(QtCore.QSize(71, 16))
        self.vehicleRegistrationLabel_2.setMaximumSize(QtCore.QSize(71, 16))
        self.vehicleRegistrationLabel_2.setText(QtGui.QApplication.translate("materialWidget", "Registration", None, QtGui.QApplication.UnicodeUTF8))
        self.vehicleRegistrationLabel_2.setObjectName(_fromUtf8("vehicleRegistrationLabel_2"))
        self.gridLayout.addWidget(self.vehicleRegistrationLabel_2, 3, 0, 1, 2)
        self.vehicleRegistrationEdit = ValidatingLineEdit(self.vehicleBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vehicleRegistrationEdit.sizePolicy().hasHeightForWidth())
        self.vehicleRegistrationEdit.setSizePolicy(sizePolicy)
        self.vehicleRegistrationEdit.setMinimumSize(QtCore.QSize(91, 25))
        self.vehicleRegistrationEdit.setMaximumSize(QtCore.QSize(91, 25))
        self.vehicleRegistrationEdit.setToolTip(QtGui.QApplication.translate("materialWidget", "Enter valid UK vehicle registration number.", None, QtGui.QApplication.UnicodeUTF8))
        self.vehicleRegistrationEdit.setWhatsThis(QtGui.QApplication.translate("materialWidget", "The analog clock widget displays the current time.", None, QtGui.QApplication.UnicodeUTF8))
        self.vehicleRegistrationEdit.setStyleSheet(_fromUtf8("QLineEdit {background-color: red;}"))
        self.vehicleRegistrationEdit.setProperty("regexString", QtGui.QApplication.translate("materialWidget", "post2001Reg", None, QtGui.QApplication.UnicodeUTF8))
        self.vehicleRegistrationEdit.setObjectName(_fromUtf8("vehicleRegistrationEdit"))
        self.gridLayout.addWidget(self.vehicleRegistrationEdit, 3, 2, 1, 1)
        self.vinLabel = QtGui.QLabel(self.vehicleBox)
        self.vinLabel.setMaximumSize(QtCore.QSize(21, 16))
        self.vinLabel.setText(QtGui.QApplication.translate("materialWidget", "VIN", None, QtGui.QApplication.UnicodeUTF8))
        self.vinLabel.setObjectName(_fromUtf8("vinLabel"))
        self.gridLayout.addWidget(self.vinLabel, 4, 0, 1, 1)
        self.vinEdit = ValidatingLineEdit(self.vehicleBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vinEdit.sizePolicy().hasHeightForWidth())
        self.vinEdit.setSizePolicy(sizePolicy)
        self.vinEdit.setMinimumSize(QtCore.QSize(0, 25))
        self.vinEdit.setMaximumSize(QtCore.QSize(183, 25))
        self.vinEdit.setToolTip(QtGui.QApplication.translate("materialWidget", "Enter valid VIN number.", None, QtGui.QApplication.UnicodeUTF8))
        self.vinEdit.setWhatsThis(QtGui.QApplication.translate("materialWidget", "The analog clock widget displays the current time.", None, QtGui.QApplication.UnicodeUTF8))
        self.vinEdit.setStyleSheet(_fromUtf8(""))
        self.vinEdit.setProperty("regexString", QtGui.QApplication.translate("materialWidget", "vin", None, QtGui.QApplication.UnicodeUTF8))
        self.vinEdit.setObjectName(_fromUtf8("vinEdit"))
        self.gridLayout.addWidget(self.vinEdit, 4, 1, 1, 2)
        self.idLabel = QtGui.QLabel(self.vehicleBox)
        self.idLabel.setMinimumSize(QtCore.QSize(16, 16))
        self.idLabel.setMaximumSize(QtCore.QSize(16, 16))
        self.idLabel.setText(QtGui.QApplication.translate("materialWidget", "ID", None, QtGui.QApplication.UnicodeUTF8))
        self.idLabel.setObjectName(_fromUtf8("idLabel"))
        self.gridLayout.addWidget(self.idLabel, 5, 0, 1, 1)
        self.idCombobox = QtGui.QComboBox(self.vehicleBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.idCombobox.sizePolicy().hasHeightForWidth())
        self.idCombobox.setSizePolicy(sizePolicy)
        self.idCombobox.setMinimumSize(QtCore.QSize(121, 25))
        self.idCombobox.setMaximumSize(QtCore.QSize(121, 25))
        self.idCombobox.setToolTip(QtGui.QApplication.translate("materialWidget", "Select ID status.", None, QtGui.QApplication.UnicodeUTF8))
        self.idCombobox.setObjectName(_fromUtf8("idCombobox"))
        self.idCombobox.addItem(_fromUtf8(""))
        self.idCombobox.setItemText(0, QtGui.QApplication.translate("materialWidget", "Checked", None, QtGui.QApplication.UnicodeUTF8))
        self.idCombobox.addItem(_fromUtf8(""))
        self.idCombobox.setItemText(1, QtGui.QApplication.translate("materialWidget", "Known", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLayout.addWidget(self.idCombobox, 5, 1, 1, 2)
        self.horizontalLayout_2.addWidget(self.vehicleBox)

        self.retranslateUi(materialWidget)
        QtCore.QMetaObject.connectSlotsByName(materialWidget)

    def retranslateUi(self, materialWidget):
        item = self.materialTable.horizontalHeaderItem(0)
        item = self.materialTable.horizontalHeaderItem(1)

from custom_widgets.validatingLineEdit import ValidatingLineEdit
