# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_ticket_widget_design.ui'
#
# Created: Thu Sep 22 11:19:28 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_newTicketWidget(object):
    def setupUi(self, newTicketWidget):
        newTicketWidget.setObjectName(_fromUtf8("newTicketWidget"))
        newTicketWidget.resize(886, 531)
        newTicketWidget.setWindowTitle(QtGui.QApplication.translate("newTicketWidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.payloadsGroupBox = QtGui.QGroupBox(newTicketWidget)
        self.payloadsGroupBox.setGeometry(QtCore.QRect(280, 10, 601, 521))
        self.payloadsGroupBox.setTitle(QtGui.QApplication.translate("newTicketWidget", "Payloads", None, QtGui.QApplication.UnicodeUTF8))
        self.payloadsGroupBox.setObjectName(_fromUtf8("payloadsGroupBox"))
        self.payloadTableWidget = PayloadTableWidget(self.payloadsGroupBox)
        self.payloadTableWidget.setGeometry(QtCore.QRect(20, 370, 331, 141))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.payloadTableWidget.sizePolicy().hasHeightForWidth())
        self.payloadTableWidget.setSizePolicy(sizePolicy)
        self.payloadTableWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.payloadTableWidget.setMaximumSize(QtCore.QSize(8000, 800))
        self.payloadTableWidget.setToolTip(QtGui.QApplication.translate("newTicketWidget", "Double-click blue vehicle text to view/edit vehicle details.\n"
"Click the red \'Delete\' to remove.", None, QtGui.QApplication.UnicodeUTF8))
        self.payloadTableWidget.setWhatsThis(QtGui.QApplication.translate("newTicketWidget", "Extra functions for paylod widget.", None, QtGui.QApplication.UnicodeUTF8))
        self.payloadTableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.payloadTableWidget.setTabKeyNavigation(True)
        self.payloadTableWidget.setProperty("showDropIndicator", False)
        self.payloadTableWidget.setDragDropOverwriteMode(False)
        self.payloadTableWidget.setRowCount(0)
        self.payloadTableWidget.setColumnCount(4)
        self.payloadTableWidget.setObjectName(_fromUtf8("payloadTableWidget"))
        self.payloadTableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.payloadTableWidget.horizontalHeader().setMinimumSectionSize(25)
        self.payloadTableWidget.horizontalHeader().setStretchLastSection(True)
        self.vehicleGroupBox = QtGui.QGroupBox(self.payloadsGroupBox)
        self.vehicleGroupBox.setEnabled(False)
        self.vehicleGroupBox.setGeometry(QtCore.QRect(340, 10, 228, 217))
        self.vehicleGroupBox.setTitle(QtGui.QApplication.translate("newTicketWidget", "Vehicle", None, QtGui.QApplication.UnicodeUTF8))
        self.vehicleGroupBox.setCheckable(False)
        self.vehicleGroupBox.setObjectName(_fromUtf8("vehicleGroupBox"))
        self.gridLayout = QtGui.QGridLayout(self.vehicleGroupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.makeLabel = QtGui.QLabel(self.vehicleGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.makeLabel.sizePolicy().hasHeightForWidth())
        self.makeLabel.setSizePolicy(sizePolicy)
        self.makeLabel.setMinimumSize(QtCore.QSize(32, 16))
        self.makeLabel.setMaximumSize(QtCore.QSize(32, 16))
        self.makeLabel.setText(QtGui.QApplication.translate("newTicketWidget", "Make", None, QtGui.QApplication.UnicodeUTF8))
        self.makeLabel.setObjectName(_fromUtf8("makeLabel"))
        self.gridLayout.addWidget(self.makeLabel, 0, 0, 1, 1)
        self.makeLineEdit = ValidatingLineEdit(self.vehicleGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.makeLineEdit.sizePolicy().hasHeightForWidth())
        self.makeLineEdit.setSizePolicy(sizePolicy)
        self.makeLineEdit.setMinimumSize(QtCore.QSize(161, 25))
        self.makeLineEdit.setMaximumSize(QtCore.QSize(161, 25))
        self.makeLineEdit.setToolTip(QtGui.QApplication.translate("newTicketWidget", "Enter vehicle make.", None, QtGui.QApplication.UnicodeUTF8))
        self.makeLineEdit.setWhatsThis(QtGui.QApplication.translate("newTicketWidget", "The analog clock widget displays the current time.", None, QtGui.QApplication.UnicodeUTF8))
        self.makeLineEdit.setStyleSheet(_fromUtf8("QLineEdit {background-color: red;}"))
        self.makeLineEdit.setProperty("regexString", QtGui.QApplication.translate("newTicketWidget", "street", None, QtGui.QApplication.UnicodeUTF8))
        self.makeLineEdit.setObjectName(_fromUtf8("makeLineEdit"))
        self.gridLayout.addWidget(self.makeLineEdit, 0, 1, 1, 2)
        self.modelLabel = QtGui.QLabel(self.vehicleGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modelLabel.sizePolicy().hasHeightForWidth())
        self.modelLabel.setSizePolicy(sizePolicy)
        self.modelLabel.setMinimumSize(QtCore.QSize(36, 16))
        self.modelLabel.setMaximumSize(QtCore.QSize(36, 16))
        self.modelLabel.setText(QtGui.QApplication.translate("newTicketWidget", "Model", None, QtGui.QApplication.UnicodeUTF8))
        self.modelLabel.setObjectName(_fromUtf8("modelLabel"))
        self.gridLayout.addWidget(self.modelLabel, 1, 0, 1, 1)
        self.modelLineEdit = ValidatingLineEdit(self.vehicleGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modelLineEdit.sizePolicy().hasHeightForWidth())
        self.modelLineEdit.setSizePolicy(sizePolicy)
        self.modelLineEdit.setMinimumSize(QtCore.QSize(161, 25))
        self.modelLineEdit.setMaximumSize(QtCore.QSize(161, 25))
        self.modelLineEdit.setToolTip(QtGui.QApplication.translate("newTicketWidget", "Enter vehicle model.", None, QtGui.QApplication.UnicodeUTF8))
        self.modelLineEdit.setWhatsThis(QtGui.QApplication.translate("newTicketWidget", "The analog clock widget displays the current time.", None, QtGui.QApplication.UnicodeUTF8))
        self.modelLineEdit.setProperty("regexString", QtGui.QApplication.translate("newTicketWidget", "model", None, QtGui.QApplication.UnicodeUTF8))
        self.modelLineEdit.setObjectName(_fromUtf8("modelLineEdit"))
        self.gridLayout.addWidget(self.modelLineEdit, 1, 1, 1, 2)
        self.colourLabel = QtGui.QLabel(self.vehicleGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colourLabel.sizePolicy().hasHeightForWidth())
        self.colourLabel.setSizePolicy(sizePolicy)
        self.colourLabel.setMinimumSize(QtCore.QSize(39, 16))
        self.colourLabel.setMaximumSize(QtCore.QSize(39, 16))
        self.colourLabel.setText(QtGui.QApplication.translate("newTicketWidget", "Colour", None, QtGui.QApplication.UnicodeUTF8))
        self.colourLabel.setObjectName(_fromUtf8("colourLabel"))
        self.gridLayout.addWidget(self.colourLabel, 2, 0, 1, 1)
        self.colourCombobox = QtGui.QComboBox(self.vehicleGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colourCombobox.sizePolicy().hasHeightForWidth())
        self.colourCombobox.setSizePolicy(sizePolicy)
        self.colourCombobox.setMinimumSize(QtCore.QSize(121, 25))
        self.colourCombobox.setMaximumSize(QtCore.QSize(121, 25))
        self.colourCombobox.setToolTip(QtGui.QApplication.translate("newTicketWidget", "Select vehicle colour.", None, QtGui.QApplication.UnicodeUTF8))
        self.colourCombobox.setObjectName(_fromUtf8("colourCombobox"))
        self.colourCombobox.addItem(_fromUtf8(""))
        self.colourCombobox.setItemText(0, QtGui.QApplication.translate("newTicketWidget", "Black", None, QtGui.QApplication.UnicodeUTF8))
        self.colourCombobox.addItem(_fromUtf8(""))
        self.colourCombobox.setItemText(1, QtGui.QApplication.translate("newTicketWidget", "Blue", None, QtGui.QApplication.UnicodeUTF8))
        self.colourCombobox.addItem(_fromUtf8(""))
        self.colourCombobox.setItemText(2, QtGui.QApplication.translate("newTicketWidget", "Brown", None, QtGui.QApplication.UnicodeUTF8))
        self.colourCombobox.addItem(_fromUtf8(""))
        self.colourCombobox.setItemText(3, QtGui.QApplication.translate("newTicketWidget", "Green", None, QtGui.QApplication.UnicodeUTF8))
        self.colourCombobox.addItem(_fromUtf8(""))
        self.colourCombobox.setItemText(4, QtGui.QApplication.translate("newTicketWidget", "Grey", None, QtGui.QApplication.UnicodeUTF8))
        self.colourCombobox.addItem(_fromUtf8(""))
        self.colourCombobox.setItemText(5, QtGui.QApplication.translate("newTicketWidget", "Orange", None, QtGui.QApplication.UnicodeUTF8))
        self.colourCombobox.addItem(_fromUtf8(""))
        self.colourCombobox.setItemText(6, QtGui.QApplication.translate("newTicketWidget", "Pink", None, QtGui.QApplication.UnicodeUTF8))
        self.colourCombobox.addItem(_fromUtf8(""))
        self.colourCombobox.setItemText(7, QtGui.QApplication.translate("newTicketWidget", "Purple", None, QtGui.QApplication.UnicodeUTF8))
        self.colourCombobox.addItem(_fromUtf8(""))
        self.colourCombobox.setItemText(8, QtGui.QApplication.translate("newTicketWidget", "Red", None, QtGui.QApplication.UnicodeUTF8))
        self.colourCombobox.addItem(_fromUtf8(""))
        self.colourCombobox.setItemText(9, QtGui.QApplication.translate("newTicketWidget", "White", None, QtGui.QApplication.UnicodeUTF8))
        self.colourCombobox.addItem(_fromUtf8(""))
        self.colourCombobox.setItemText(10, QtGui.QApplication.translate("newTicketWidget", "Yellow", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLayout.addWidget(self.colourCombobox, 2, 1, 1, 2)
        self.vehicleRegistrationLabel_2 = QtGui.QLabel(self.vehicleGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vehicleRegistrationLabel_2.sizePolicy().hasHeightForWidth())
        self.vehicleRegistrationLabel_2.setSizePolicy(sizePolicy)
        self.vehicleRegistrationLabel_2.setMinimumSize(QtCore.QSize(71, 16))
        self.vehicleRegistrationLabel_2.setMaximumSize(QtCore.QSize(71, 16))
        self.vehicleRegistrationLabel_2.setText(QtGui.QApplication.translate("newTicketWidget", "Registration", None, QtGui.QApplication.UnicodeUTF8))
        self.vehicleRegistrationLabel_2.setObjectName(_fromUtf8("vehicleRegistrationLabel_2"))
        self.gridLayout.addWidget(self.vehicleRegistrationLabel_2, 3, 0, 1, 2)
        self.vehicleRegistrationLineEdit = ValidatingLineEdit(self.vehicleGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vehicleRegistrationLineEdit.sizePolicy().hasHeightForWidth())
        self.vehicleRegistrationLineEdit.setSizePolicy(sizePolicy)
        self.vehicleRegistrationLineEdit.setMinimumSize(QtCore.QSize(91, 25))
        self.vehicleRegistrationLineEdit.setMaximumSize(QtCore.QSize(91, 25))
        self.vehicleRegistrationLineEdit.setToolTip(QtGui.QApplication.translate("newTicketWidget", "Enter valid UK vehicle registration number.", None, QtGui.QApplication.UnicodeUTF8))
        self.vehicleRegistrationLineEdit.setWhatsThis(QtGui.QApplication.translate("newTicketWidget", "The analog clock widget displays the current time.", None, QtGui.QApplication.UnicodeUTF8))
        self.vehicleRegistrationLineEdit.setStyleSheet(_fromUtf8("QLineEdit {background-color: red;}"))
        self.vehicleRegistrationLineEdit.setProperty("regexString", QtGui.QApplication.translate("newTicketWidget", "post2001Reg", None, QtGui.QApplication.UnicodeUTF8))
        self.vehicleRegistrationLineEdit.setObjectName(_fromUtf8("vehicleRegistrationLineEdit"))
        self.gridLayout.addWidget(self.vehicleRegistrationLineEdit, 3, 2, 1, 1)
        self.vinLabel = QtGui.QLabel(self.vehicleGroupBox)
        self.vinLabel.setMaximumSize(QtCore.QSize(21, 16))
        self.vinLabel.setText(QtGui.QApplication.translate("newTicketWidget", "VIN", None, QtGui.QApplication.UnicodeUTF8))
        self.vinLabel.setObjectName(_fromUtf8("vinLabel"))
        self.gridLayout.addWidget(self.vinLabel, 4, 0, 1, 1)
        self.vinLineEdit = ValidatingLineEdit(self.vehicleGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vinLineEdit.sizePolicy().hasHeightForWidth())
        self.vinLineEdit.setSizePolicy(sizePolicy)
        self.vinLineEdit.setMinimumSize(QtCore.QSize(0, 25))
        self.vinLineEdit.setMaximumSize(QtCore.QSize(183, 25))
        self.vinLineEdit.setToolTip(QtGui.QApplication.translate("newTicketWidget", "Enter valid VIN number.", None, QtGui.QApplication.UnicodeUTF8))
        self.vinLineEdit.setWhatsThis(QtGui.QApplication.translate("newTicketWidget", "The analog clock widget displays the current time.", None, QtGui.QApplication.UnicodeUTF8))
        self.vinLineEdit.setProperty("regexString", QtGui.QApplication.translate("newTicketWidget", "vin", None, QtGui.QApplication.UnicodeUTF8))
        self.vinLineEdit.setObjectName(_fromUtf8("vinLineEdit"))
        self.gridLayout.addWidget(self.vinLineEdit, 4, 1, 1, 2)
        self.idLabel = QtGui.QLabel(self.vehicleGroupBox)
        self.idLabel.setMinimumSize(QtCore.QSize(16, 16))
        self.idLabel.setMaximumSize(QtCore.QSize(16, 16))
        self.idLabel.setText(QtGui.QApplication.translate("newTicketWidget", "ID", None, QtGui.QApplication.UnicodeUTF8))
        self.idLabel.setObjectName(_fromUtf8("idLabel"))
        self.gridLayout.addWidget(self.idLabel, 5, 0, 1, 1)
        self.idCombobox = QtGui.QComboBox(self.vehicleGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.idCombobox.sizePolicy().hasHeightForWidth())
        self.idCombobox.setSizePolicy(sizePolicy)
        self.idCombobox.setMinimumSize(QtCore.QSize(121, 25))
        self.idCombobox.setMaximumSize(QtCore.QSize(121, 25))
        self.idCombobox.setToolTip(QtGui.QApplication.translate("newTicketWidget", "Select ID status.", None, QtGui.QApplication.UnicodeUTF8))
        self.idCombobox.setObjectName(_fromUtf8("idCombobox"))
        self.idCombobox.addItem(_fromUtf8(""))
        self.idCombobox.setItemText(0, QtGui.QApplication.translate("newTicketWidget", "Checked", None, QtGui.QApplication.UnicodeUTF8))
        self.idCombobox.addItem(_fromUtf8(""))
        self.idCombobox.setItemText(1, QtGui.QApplication.translate("newTicketWidget", "Known", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLayout.addWidget(self.idCombobox, 5, 1, 1, 2)
        self.groupBox = QtGui.QGroupBox(self.payloadsGroupBox)
        self.groupBox.setGeometry(QtCore.QRect(60, 280, 256, 88))
        self.groupBox.setTitle(QtGui.QApplication.translate("newTicketWidget", "Payload Total", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.payloadTotalLabel = QtGui.QLabel(self.groupBox)
        self.payloadTotalLabel.setText(QtGui.QApplication.translate("newTicketWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">$ 340.00</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.payloadTotalLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.payloadTotalLabel.setObjectName(_fromUtf8("payloadTotalLabel"))
        self.verticalLayout.addWidget(self.payloadTotalLabel)
        self.pushButton = QtGui.QPushButton(self.groupBox)
        self.pushButton.setText(QtGui.QApplication.translate("newTicketWidget", "Custom total", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout.addWidget(self.pushButton)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.line = QtGui.QFrame(self.groupBox)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout.addWidget(self.line)
        spacerItem1 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.addPayloadButton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addPayloadButton.sizePolicy().hasHeightForWidth())
        self.addPayloadButton.setSizePolicy(sizePolicy)
        self.addPayloadButton.setMinimumSize(QtCore.QSize(81, 0))
        self.addPayloadButton.setText(QtGui.QApplication.translate("newTicketWidget", "Add payload", None, QtGui.QApplication.UnicodeUTF8))
        self.addPayloadButton.setObjectName(_fromUtf8("addPayloadButton"))
        self.horizontalLayout.addWidget(self.addPayloadButton)
        self.layoutWidget = QtGui.QWidget(self.payloadsGroupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(400, 390, 133, 98))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox_2 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_2.setTitle(QtGui.QApplication.translate("newTicketWidget", "Ticket total", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setText(QtGui.QApplication.translate("newTicketWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">$ 3400.00</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.reviewTicketButton = QtGui.QCommandLinkButton(self.layoutWidget)
        self.reviewTicketButton.setEnabled(False)
        self.reviewTicketButton.setMinimumSize(QtCore.QSize(131, 0))
        self.reviewTicketButton.setMaximumSize(QtCore.QSize(131, 16777215))
        self.reviewTicketButton.setText(QtGui.QApplication.translate("newTicketWidget", "Review ticket", None, QtGui.QApplication.UnicodeUTF8))
        self.reviewTicketButton.setObjectName(_fromUtf8("reviewTicketButton"))
        self.verticalLayout_3.addWidget(self.reviewTicketButton)
        self.payloadWidget = PayloadWidget(self.payloadsGroupBox)
        self.payloadWidget.setGeometry(QtCore.QRect(10, 20, 341, 281))
        self.payloadWidget.setToolTip(QtGui.QApplication.translate("newTicketWidget", "Payload details.", None, QtGui.QApplication.UnicodeUTF8))
        self.payloadWidget.setWhatsThis(QtGui.QApplication.translate("newTicketWidget", "Payload widget.", None, QtGui.QApplication.UnicodeUTF8))
        self.payloadWidget.setObjectName(_fromUtf8("payloadWidget"))
        self.customerWidget = CustomerWidget(newTicketWidget)
        self.customerWidget.setGeometry(QtCore.QRect(0, 0, 290, 266))
        self.customerWidget.setToolTip(QtGui.QApplication.translate("newTicketWidget", "Customer details.", None, QtGui.QApplication.UnicodeUTF8))
        self.customerWidget.setWhatsThis(QtGui.QApplication.translate("newTicketWidget", "Customer details widgte.", None, QtGui.QApplication.UnicodeUTF8))
        self.customerWidget.setObjectName(_fromUtf8("customerWidget"))

        self.retranslateUi(newTicketWidget)
        QtCore.QMetaObject.connectSlotsByName(newTicketWidget)

    def retranslateUi(self, newTicketWidget):
        pass

from custom_widgets.payloadWidget import PayloadWidget
from custom_widgets.payloadTableWidget import PayloadTableWidget
from custom_widgets.customerWidget import CustomerWidget
from custom_widgets.validatingLineEdit import ValidatingLineEdit
