# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'proto_new_ticket_design.ui'
#
# Created: Thu Sep 15 16:49:24 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_newTicketWidget(object):
    def setupUi(self, newTicketWidget):
        newTicketWidget.setObjectName(_fromUtf8("newTicketWidget"))
        newTicketWidget.resize(770, 552)
        newTicketWidget.setWindowTitle(QtGui.QApplication.translate("newTicketWidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalLayout = QtGui.QHBoxLayout(newTicketWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox_2 = QtGui.QGroupBox(newTicketWidget)
        self.groupBox_2.setTitle(QtGui.QApplication.translate("newTicketWidget", "Customer", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.formLayout = QtGui.QFormLayout(self.groupBox_2)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.firstNameLabel = QtGui.QLabel(self.groupBox_2)
        self.firstNameLabel.setText(QtGui.QApplication.translate("newTicketWidget", "First name", None, QtGui.QApplication.UnicodeUTF8))
        self.firstNameLabel.setObjectName(_fromUtf8("firstNameLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.firstNameLabel)
        self.firstNameLineEdit = ValidatingLineEdit(self.groupBox_2)
        self.firstNameLineEdit.setMinimumSize(QtCore.QSize(133, 20))
        self.firstNameLineEdit.setMaximumSize(QtCore.QSize(133, 20))
        self.firstNameLineEdit.setToolTip(QtGui.QApplication.translate("newTicketWidget", "Customer first name.", None, QtGui.QApplication.UnicodeUTF8))
        self.firstNameLineEdit.setStatusTip(QtGui.QApplication.translate("newTicketWidget", "Status test", None, QtGui.QApplication.UnicodeUTF8))
        self.firstNameLineEdit.setWhatsThis(QtGui.QApplication.translate("newTicketWidget", "The analog clock widget displays the current time.", None, QtGui.QApplication.UnicodeUTF8))
        self.firstNameLineEdit.setStyleSheet(_fromUtf8("QLineEdit {background-color: red;}"))
        self.firstNameLineEdit.setProperty("regexString", QtGui.QApplication.translate("newTicketWidget", "name", None, QtGui.QApplication.UnicodeUTF8))
        self.firstNameLineEdit.setObjectName(_fromUtf8("firstNameLineEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.firstNameLineEdit)
        self.lastNameLabel = QtGui.QLabel(self.groupBox_2)
        self.lastNameLabel.setText(QtGui.QApplication.translate("newTicketWidget", "Last name", None, QtGui.QApplication.UnicodeUTF8))
        self.lastNameLabel.setObjectName(_fromUtf8("lastNameLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lastNameLabel)
        self.lastNameLineEdit = ValidatingLineEdit(self.groupBox_2)
        self.lastNameLineEdit.setMinimumSize(QtCore.QSize(133, 20))
        self.lastNameLineEdit.setMaximumSize(QtCore.QSize(133, 20))
        self.lastNameLineEdit.setToolTip(QtGui.QApplication.translate("newTicketWidget", "Customer last name.", None, QtGui.QApplication.UnicodeUTF8))
        self.lastNameLineEdit.setWhatsThis(QtGui.QApplication.translate("newTicketWidget", "The analog clock widget displays the current time.", None, QtGui.QApplication.UnicodeUTF8))
        self.lastNameLineEdit.setStyleSheet(_fromUtf8("QLineEdit {background-color: red;}"))
        self.lastNameLineEdit.setProperty("regexString", QtGui.QApplication.translate("newTicketWidget", "name", None, QtGui.QApplication.UnicodeUTF8))
        self.lastNameLineEdit.setObjectName(_fromUtf8("lastNameLineEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lastNameLineEdit)
        self.houseNumberLabel = QtGui.QLabel(self.groupBox_2)
        self.houseNumberLabel.setText(QtGui.QApplication.translate("newTicketWidget", "House number", None, QtGui.QApplication.UnicodeUTF8))
        self.houseNumberLabel.setObjectName(_fromUtf8("houseNumberLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.houseNumberLabel)
        self.houseNumberLineEdit = ValidatingLineEdit(self.groupBox_2)
        self.houseNumberLineEdit.setMinimumSize(QtCore.QSize(51, 20))
        self.houseNumberLineEdit.setMaximumSize(QtCore.QSize(51, 20))
        self.houseNumberLineEdit.setToolTip(QtGui.QApplication.translate("newTicketWidget", "Customer house number.", None, QtGui.QApplication.UnicodeUTF8))
        self.houseNumberLineEdit.setWhatsThis(QtGui.QApplication.translate("newTicketWidget", "The analog clock widget displays the current time.", None, QtGui.QApplication.UnicodeUTF8))
        self.houseNumberLineEdit.setStyleSheet(_fromUtf8("QLineEdit {background-color: red;}"))
        self.houseNumberLineEdit.setProperty("regexString", QtGui.QApplication.translate("newTicketWidget", "houseNumber", None, QtGui.QApplication.UnicodeUTF8))
        self.houseNumberLineEdit.setObjectName(_fromUtf8("houseNumberLineEdit"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.houseNumberLineEdit)
        self.streetLabel = QtGui.QLabel(self.groupBox_2)
        self.streetLabel.setText(QtGui.QApplication.translate("newTicketWidget", "Street", None, QtGui.QApplication.UnicodeUTF8))
        self.streetLabel.setObjectName(_fromUtf8("streetLabel"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.streetLabel)
        self.streetLineEdit = ValidatingLineEdit(self.groupBox_2)
        self.streetLineEdit.setMinimumSize(QtCore.QSize(133, 20))
        self.streetLineEdit.setMaximumSize(QtCore.QSize(133, 20))
        self.streetLineEdit.setToolTip(QtGui.QApplication.translate("newTicketWidget", "Customer address street.", None, QtGui.QApplication.UnicodeUTF8))
        self.streetLineEdit.setWhatsThis(QtGui.QApplication.translate("newTicketWidget", "The analog clock widget displays the current time.", None, QtGui.QApplication.UnicodeUTF8))
        self.streetLineEdit.setStyleSheet(_fromUtf8("QLineEdit {background-color: red;}"))
        self.streetLineEdit.setProperty("regexString", QtGui.QApplication.translate("newTicketWidget", "street", None, QtGui.QApplication.UnicodeUTF8))
        self.streetLineEdit.setObjectName(_fromUtf8("streetLineEdit"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.streetLineEdit)
        self.townLabel = QtGui.QLabel(self.groupBox_2)
        self.townLabel.setText(QtGui.QApplication.translate("newTicketWidget", "Town", None, QtGui.QApplication.UnicodeUTF8))
        self.townLabel.setObjectName(_fromUtf8("townLabel"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.townLabel)
        self.townLineEdit = ValidatingLineEdit(self.groupBox_2)
        self.townLineEdit.setMinimumSize(QtCore.QSize(101, 20))
        self.townLineEdit.setMaximumSize(QtCore.QSize(101, 20))
        self.townLineEdit.setToolTip(QtGui.QApplication.translate("newTicketWidget", "Customer address town.", None, QtGui.QApplication.UnicodeUTF8))
        self.townLineEdit.setWhatsThis(QtGui.QApplication.translate("newTicketWidget", "The analog clock widget displays the current time.", None, QtGui.QApplication.UnicodeUTF8))
        self.townLineEdit.setStyleSheet(_fromUtf8("QLineEdit {background-color: red;}"))
        self.townLineEdit.setProperty("regexString", QtGui.QApplication.translate("newTicketWidget", "town", None, QtGui.QApplication.UnicodeUTF8))
        self.townLineEdit.setObjectName(_fromUtf8("townLineEdit"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.townLineEdit)
        self.postcodeLabel = QtGui.QLabel(self.groupBox_2)
        self.postcodeLabel.setText(QtGui.QApplication.translate("newTicketWidget", "Postcode", None, QtGui.QApplication.UnicodeUTF8))
        self.postcodeLabel.setObjectName(_fromUtf8("postcodeLabel"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.postcodeLabel)
        self.postcodeLineEdit = ValidatingLineEdit(self.groupBox_2)
        self.postcodeLineEdit.setMinimumSize(QtCore.QSize(51, 20))
        self.postcodeLineEdit.setMaximumSize(QtCore.QSize(71, 20))
        self.postcodeLineEdit.setToolTip(QtGui.QApplication.translate("newTicketWidget", "Customer address postcode.", None, QtGui.QApplication.UnicodeUTF8))
        self.postcodeLineEdit.setWhatsThis(QtGui.QApplication.translate("newTicketWidget", "The analog clock widget displays the current time.", None, QtGui.QApplication.UnicodeUTF8))
        self.postcodeLineEdit.setStyleSheet(_fromUtf8("QLineEdit {background-color: red;}"))
        self.postcodeLineEdit.setProperty("regexString", QtGui.QApplication.translate("newTicketWidget", "postcode", None, QtGui.QApplication.UnicodeUTF8))
        self.postcodeLineEdit.setObjectName(_fromUtf8("postcodeLineEdit"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.postcodeLineEdit)
        self.vehicleRegistrationLabel = QtGui.QLabel(self.groupBox_2)
        self.vehicleRegistrationLabel.setText(QtGui.QApplication.translate("newTicketWidget", "Vehicle Registration", None, QtGui.QApplication.UnicodeUTF8))
        self.vehicleRegistrationLabel.setObjectName(_fromUtf8("vehicleRegistrationLabel"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.vehicleRegistrationLabel)
        self.vehicleRegistrationLineEdit = ValidatingLineEdit(self.groupBox_2)
        self.vehicleRegistrationLineEdit.setMinimumSize(QtCore.QSize(71, 20))
        self.vehicleRegistrationLineEdit.setMaximumSize(QtCore.QSize(71, 20))
        self.vehicleRegistrationLineEdit.setToolTip(QtGui.QApplication.translate("newTicketWidget", "Customer\'s vehicle registration number.", None, QtGui.QApplication.UnicodeUTF8))
        self.vehicleRegistrationLineEdit.setWhatsThis(QtGui.QApplication.translate("newTicketWidget", "The analog clock widget displays the current time.", None, QtGui.QApplication.UnicodeUTF8))
        self.vehicleRegistrationLineEdit.setStyleSheet(_fromUtf8("QLineEdit {background-color: red;}"))
        self.vehicleRegistrationLineEdit.setProperty("regexString", QtGui.QApplication.translate("newTicketWidget", "post2001Reg", None, QtGui.QApplication.UnicodeUTF8))
        self.vehicleRegistrationLineEdit.setObjectName(_fromUtf8("vehicleRegistrationLineEdit"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.vehicleRegistrationLineEdit)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(newTicketWidget)
        self.groupBox_3.setTitle(QtGui.QApplication.translate("newTicketWidget", "Vehicle", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.typeLabel = QtGui.QLabel(self.groupBox_3)
        self.typeLabel.setMinimumSize(QtCore.QSize(31, 16))
        self.typeLabel.setMaximumSize(QtCore.QSize(31, 16))
        self.typeLabel.setText(QtGui.QApplication.translate("newTicketWidget", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.typeLabel.setObjectName(_fromUtf8("typeLabel"))
        self.gridLayout.addWidget(self.typeLabel, 0, 0, 1, 1)
        self.typeCombobox = QtGui.QComboBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typeCombobox.sizePolicy().hasHeightForWidth())
        self.typeCombobox.setSizePolicy(sizePolicy)
        self.typeCombobox.setMinimumSize(QtCore.QSize(161, 25))
        self.typeCombobox.setMaximumSize(QtCore.QSize(161, 25))
        self.typeCombobox.setToolTip(QtGui.QApplication.translate("newTicketWidget", "Select vehicle type.", None, QtGui.QApplication.UnicodeUTF8))
        self.typeCombobox.setObjectName(_fromUtf8("typeCombobox"))
        self.gridLayout.addWidget(self.typeCombobox, 0, 1, 1, 3)
        self.makeLabel = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.makeLabel.sizePolicy().hasHeightForWidth())
        self.makeLabel.setSizePolicy(sizePolicy)
        self.makeLabel.setMinimumSize(QtCore.QSize(32, 16))
        self.makeLabel.setMaximumSize(QtCore.QSize(32, 16))
        self.makeLabel.setText(QtGui.QApplication.translate("newTicketWidget", "Make", None, QtGui.QApplication.UnicodeUTF8))
        self.makeLabel.setObjectName(_fromUtf8("makeLabel"))
        self.gridLayout.addWidget(self.makeLabel, 1, 0, 1, 1)
        self.makeLineEdit = ValidatingLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.makeLineEdit.sizePolicy().hasHeightForWidth())
        self.makeLineEdit.setSizePolicy(sizePolicy)
        self.makeLineEdit.setMinimumSize(QtCore.QSize(161, 25))
        self.makeLineEdit.setMaximumSize(QtCore.QSize(161, 25))
        self.makeLineEdit.setToolTip(QtGui.QApplication.translate("newTicketWidget", "Enter vehicle make.", None, QtGui.QApplication.UnicodeUTF8))
        self.makeLineEdit.setWhatsThis(QtGui.QApplication.translate("newTicketWidget", "The analog clock widget displays the current time.", None, QtGui.QApplication.UnicodeUTF8))
        self.makeLineEdit.setStyleSheet(_fromUtf8("QLineEdit {background-color: red;}"))
        self.makeLineEdit.setProperty("regexString", QtGui.QApplication.translate("newTicketWidget", "street", None, QtGui.QApplication.UnicodeUTF8))
        self.makeLineEdit.setObjectName(_fromUtf8("makeLineEdit"))
        self.gridLayout.addWidget(self.makeLineEdit, 1, 1, 1, 3)
        self.modelLabel = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modelLabel.sizePolicy().hasHeightForWidth())
        self.modelLabel.setSizePolicy(sizePolicy)
        self.modelLabel.setMinimumSize(QtCore.QSize(36, 16))
        self.modelLabel.setMaximumSize(QtCore.QSize(36, 16))
        self.modelLabel.setText(QtGui.QApplication.translate("newTicketWidget", "Model", None, QtGui.QApplication.UnicodeUTF8))
        self.modelLabel.setObjectName(_fromUtf8("modelLabel"))
        self.gridLayout.addWidget(self.modelLabel, 2, 0, 1, 1)
        self.modelLineEdit = ValidatingLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modelLineEdit.sizePolicy().hasHeightForWidth())
        self.modelLineEdit.setSizePolicy(sizePolicy)
        self.modelLineEdit.setMinimumSize(QtCore.QSize(161, 25))
        self.modelLineEdit.setMaximumSize(QtCore.QSize(161, 25))
        self.modelLineEdit.setToolTip(QtGui.QApplication.translate("newTicketWidget", "Enter vehicle model.", None, QtGui.QApplication.UnicodeUTF8))
        self.modelLineEdit.setWhatsThis(QtGui.QApplication.translate("newTicketWidget", "The analog clock widget displays the current time.", None, QtGui.QApplication.UnicodeUTF8))
        self.modelLineEdit.setProperty("regexString", QtGui.QApplication.translate("newTicketWidget", "model", None, QtGui.QApplication.UnicodeUTF8))
        self.modelLineEdit.setObjectName(_fromUtf8("modelLineEdit"))
        self.gridLayout.addWidget(self.modelLineEdit, 2, 1, 1, 3)
        self.colourLabel = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colourLabel.sizePolicy().hasHeightForWidth())
        self.colourLabel.setSizePolicy(sizePolicy)
        self.colourLabel.setMinimumSize(QtCore.QSize(39, 16))
        self.colourLabel.setMaximumSize(QtCore.QSize(39, 16))
        self.colourLabel.setText(QtGui.QApplication.translate("newTicketWidget", "Colour", None, QtGui.QApplication.UnicodeUTF8))
        self.colourLabel.setObjectName(_fromUtf8("colourLabel"))
        self.gridLayout.addWidget(self.colourLabel, 3, 0, 1, 1)
        self.colourCombobox = QtGui.QComboBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colourCombobox.sizePolicy().hasHeightForWidth())
        self.colourCombobox.setSizePolicy(sizePolicy)
        self.colourCombobox.setMinimumSize(QtCore.QSize(121, 25))
        self.colourCombobox.setMaximumSize(QtCore.QSize(121, 25))
        self.colourCombobox.setToolTip(QtGui.QApplication.translate("newTicketWidget", "Select vehicle colour.", None, QtGui.QApplication.UnicodeUTF8))
        self.colourCombobox.setObjectName(_fromUtf8("colourCombobox"))
        self.colourCombobox.addItem(_fromUtf8(""))
        self.colourCombobox.setItemText(0, QtGui.QApplication.translate("newTicketWidget", "Black", None, QtGui.QApplication.UnicodeUTF8))
        self.colourCombobox.addItem(_fromUtf8(""))
        self.colourCombobox.setItemText(1, QtGui.QApplication.translate("newTicketWidget", "Blue", None, QtGui.QApplication.UnicodeUTF8))
        self.colourCombobox.addItem(_fromUtf8(""))
        self.colourCombobox.setItemText(2, QtGui.QApplication.translate("newTicketWidget", "Brown", None, QtGui.QApplication.UnicodeUTF8))
        self.colourCombobox.addItem(_fromUtf8(""))
        self.colourCombobox.setItemText(3, QtGui.QApplication.translate("newTicketWidget", "Green", None, QtGui.QApplication.UnicodeUTF8))
        self.colourCombobox.addItem(_fromUtf8(""))
        self.colourCombobox.setItemText(4, QtGui.QApplication.translate("newTicketWidget", "Grey", None, QtGui.QApplication.UnicodeUTF8))
        self.colourCombobox.addItem(_fromUtf8(""))
        self.colourCombobox.setItemText(5, QtGui.QApplication.translate("newTicketWidget", "Orange", None, QtGui.QApplication.UnicodeUTF8))
        self.colourCombobox.addItem(_fromUtf8(""))
        self.colourCombobox.setItemText(6, QtGui.QApplication.translate("newTicketWidget", "Pink", None, QtGui.QApplication.UnicodeUTF8))
        self.colourCombobox.addItem(_fromUtf8(""))
        self.colourCombobox.setItemText(7, QtGui.QApplication.translate("newTicketWidget", "Purple", None, QtGui.QApplication.UnicodeUTF8))
        self.colourCombobox.addItem(_fromUtf8(""))
        self.colourCombobox.setItemText(8, QtGui.QApplication.translate("newTicketWidget", "Red", None, QtGui.QApplication.UnicodeUTF8))
        self.colourCombobox.addItem(_fromUtf8(""))
        self.colourCombobox.setItemText(9, QtGui.QApplication.translate("newTicketWidget", "White", None, QtGui.QApplication.UnicodeUTF8))
        self.colourCombobox.addItem(_fromUtf8(""))
        self.colourCombobox.setItemText(10, QtGui.QApplication.translate("newTicketWidget", "Yellow", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLayout.addWidget(self.colourCombobox, 3, 1, 1, 3)
        self.vehicleRegistrationLabel_2 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vehicleRegistrationLabel_2.sizePolicy().hasHeightForWidth())
        self.vehicleRegistrationLabel_2.setSizePolicy(sizePolicy)
        self.vehicleRegistrationLabel_2.setMinimumSize(QtCore.QSize(71, 16))
        self.vehicleRegistrationLabel_2.setMaximumSize(QtCore.QSize(71, 16))
        self.vehicleRegistrationLabel_2.setText(QtGui.QApplication.translate("newTicketWidget", "Registration", None, QtGui.QApplication.UnicodeUTF8))
        self.vehicleRegistrationLabel_2.setObjectName(_fromUtf8("vehicleRegistrationLabel_2"))
        self.gridLayout.addWidget(self.vehicleRegistrationLabel_2, 4, 0, 1, 2)
        self.vehicleRegistrationLineEdit_2 = ValidatingLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vehicleRegistrationLineEdit_2.sizePolicy().hasHeightForWidth())
        self.vehicleRegistrationLineEdit_2.setSizePolicy(sizePolicy)
        self.vehicleRegistrationLineEdit_2.setMinimumSize(QtCore.QSize(91, 25))
        self.vehicleRegistrationLineEdit_2.setMaximumSize(QtCore.QSize(91, 25))
        self.vehicleRegistrationLineEdit_2.setToolTip(QtGui.QApplication.translate("newTicketWidget", "Enter valid UK vehicle registration number.", None, QtGui.QApplication.UnicodeUTF8))
        self.vehicleRegistrationLineEdit_2.setWhatsThis(QtGui.QApplication.translate("newTicketWidget", "The analog clock widget displays the current time.", None, QtGui.QApplication.UnicodeUTF8))
        self.vehicleRegistrationLineEdit_2.setStyleSheet(_fromUtf8("QLineEdit {background-color: red;}"))
        self.vehicleRegistrationLineEdit_2.setProperty("regexString", QtGui.QApplication.translate("newTicketWidget", "post2001Reg", None, QtGui.QApplication.UnicodeUTF8))
        self.vehicleRegistrationLineEdit_2.setObjectName(_fromUtf8("vehicleRegistrationLineEdit_2"))
        self.gridLayout.addWidget(self.vehicleRegistrationLineEdit_2, 4, 2, 1, 2)
        self.vinLabel = QtGui.QLabel(self.groupBox_3)
        self.vinLabel.setMaximumSize(QtCore.QSize(21, 16))
        self.vinLabel.setText(QtGui.QApplication.translate("newTicketWidget", "VIN", None, QtGui.QApplication.UnicodeUTF8))
        self.vinLabel.setObjectName(_fromUtf8("vinLabel"))
        self.gridLayout.addWidget(self.vinLabel, 5, 0, 1, 1)
        self.vinLineEdit = ValidatingLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vinLineEdit.sizePolicy().hasHeightForWidth())
        self.vinLineEdit.setSizePolicy(sizePolicy)
        self.vinLineEdit.setMinimumSize(QtCore.QSize(0, 25))
        self.vinLineEdit.setMaximumSize(QtCore.QSize(183, 25))
        self.vinLineEdit.setToolTip(QtGui.QApplication.translate("newTicketWidget", "Enter valid VIN number.", None, QtGui.QApplication.UnicodeUTF8))
        self.vinLineEdit.setWhatsThis(QtGui.QApplication.translate("newTicketWidget", "The analog clock widget displays the current time.", None, QtGui.QApplication.UnicodeUTF8))
        self.vinLineEdit.setProperty("regexString", QtGui.QApplication.translate("newTicketWidget", "vin", None, QtGui.QApplication.UnicodeUTF8))
        self.vinLineEdit.setObjectName(_fromUtf8("vinLineEdit"))
        self.gridLayout.addWidget(self.vinLineEdit, 5, 1, 1, 3)
        self.catalyticCheckbox = QtGui.QCheckBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.catalyticCheckbox.sizePolicy().hasHeightForWidth())
        self.catalyticCheckbox.setSizePolicy(sizePolicy)
        self.catalyticCheckbox.setMinimumSize(QtCore.QSize(141, 17))
        self.catalyticCheckbox.setMaximumSize(QtCore.QSize(141, 17))
        self.catalyticCheckbox.setToolTip(QtGui.QApplication.translate("newTicketWidget", "Enables entry of catalytic converter price.", None, QtGui.QApplication.UnicodeUTF8))
        self.catalyticCheckbox.setText(QtGui.QApplication.translate("newTicketWidget", "Catalytic Converter", None, QtGui.QApplication.UnicodeUTF8))
        self.catalyticCheckbox.setObjectName(_fromUtf8("catalyticCheckbox"))
        self.gridLayout.addWidget(self.catalyticCheckbox, 6, 0, 1, 3)
        self.catalyticLineEdit = ValidatingLineEdit(self.groupBox_3)
        self.catalyticLineEdit.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.catalyticLineEdit.sizePolicy().hasHeightForWidth())
        self.catalyticLineEdit.setSizePolicy(sizePolicy)
        self.catalyticLineEdit.setMinimumSize(QtCore.QSize(81, 25))
        self.catalyticLineEdit.setMaximumSize(QtCore.QSize(81, 25))
        self.catalyticLineEdit.setToolTip(QtGui.QApplication.translate("newTicketWidget", "Enter price for catalytic converter.", None, QtGui.QApplication.UnicodeUTF8))
        self.catalyticLineEdit.setWhatsThis(QtGui.QApplication.translate("newTicketWidget", "The analog clock widget displays the current time.", None, QtGui.QApplication.UnicodeUTF8))
        self.catalyticLineEdit.setStyleSheet(_fromUtf8("QLineEdit {background-color: red;}"))
        self.catalyticLineEdit.setProperty("regexString", QtGui.QApplication.translate("newTicketWidget", "value", None, QtGui.QApplication.UnicodeUTF8))
        self.catalyticLineEdit.setObjectName(_fromUtf8("catalyticLineEdit"))
        self.gridLayout.addWidget(self.catalyticLineEdit, 6, 3, 1, 1)
        self.idLabel = QtGui.QLabel(self.groupBox_3)
        self.idLabel.setMinimumSize(QtCore.QSize(16, 16))
        self.idLabel.setMaximumSize(QtCore.QSize(16, 16))
        self.idLabel.setText(QtGui.QApplication.translate("newTicketWidget", "ID", None, QtGui.QApplication.UnicodeUTF8))
        self.idLabel.setObjectName(_fromUtf8("idLabel"))
        self.gridLayout.addWidget(self.idLabel, 7, 0, 1, 1)
        self.idCombobox = QtGui.QComboBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.idCombobox.sizePolicy().hasHeightForWidth())
        self.idCombobox.setSizePolicy(sizePolicy)
        self.idCombobox.setMinimumSize(QtCore.QSize(121, 25))
        self.idCombobox.setMaximumSize(QtCore.QSize(121, 25))
        self.idCombobox.setToolTip(QtGui.QApplication.translate("newTicketWidget", "Select ID status.", None, QtGui.QApplication.UnicodeUTF8))
        self.idCombobox.setObjectName(_fromUtf8("idCombobox"))
        self.idCombobox.addItem(_fromUtf8(""))
        self.idCombobox.setItemText(0, QtGui.QApplication.translate("newTicketWidget", "Checked", None, QtGui.QApplication.UnicodeUTF8))
        self.idCombobox.addItem(_fromUtf8(""))
        self.idCombobox.setItemText(1, QtGui.QApplication.translate("newTicketWidget", "Known", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLayout.addWidget(self.idCombobox, 7, 1, 1, 3)
        self.rejectButton = QtGui.QPushButton(self.groupBox_3)
        self.rejectButton.setMinimumSize(QtCore.QSize(80, 26))
        self.rejectButton.setMaximumSize(QtCore.QSize(80, 26))
        self.rejectButton.setToolTip(QtGui.QApplication.translate("newTicketWidget", "Closes dialog and forgets changes.", None, QtGui.QApplication.UnicodeUTF8))
        self.rejectButton.setText(QtGui.QApplication.translate("newTicketWidget", "Reject", None, QtGui.QApplication.UnicodeUTF8))
        self.rejectButton.setObjectName(_fromUtf8("rejectButton"))
        self.gridLayout.addWidget(self.rejectButton, 8, 0, 1, 2)
        self.acceptButton = QtGui.QPushButton(self.groupBox_3)
        self.acceptButton.setEnabled(False)
        self.acceptButton.setMinimumSize(QtCore.QSize(80, 26))
        self.acceptButton.setMaximumSize(QtCore.QSize(80, 26))
        self.acceptButton.setToolTip(QtGui.QApplication.translate("newTicketWidget", "Closes dialog and saves changes.", None, QtGui.QApplication.UnicodeUTF8))
        self.acceptButton.setText(QtGui.QApplication.translate("newTicketWidget", "Accept", None, QtGui.QApplication.UnicodeUTF8))
        self.acceptButton.setObjectName(_fromUtf8("acceptButton"))
        self.gridLayout.addWidget(self.acceptButton, 8, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.groupBox = QtGui.QGroupBox(newTicketWidget)
        self.groupBox.setTitle(QtGui.QApplication.translate("newTicketWidget", "Payloads", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setText(QtGui.QApplication.translate("newTicketWidget", "Gross", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.grossWeightLineEdit = GrossWeightLineEdit(self.groupBox)
        self.grossWeightLineEdit.setMinimumSize(QtCore.QSize(71, 20))
        self.grossWeightLineEdit.setMaximumSize(QtCore.QSize(71, 20))
        self.grossWeightLineEdit.setToolTip(QtGui.QApplication.translate("newTicketWidget", "Enter gross weight. Fraction must be .5 or .0.", None, QtGui.QApplication.UnicodeUTF8))
        self.grossWeightLineEdit.setWhatsThis(QtGui.QApplication.translate("newTicketWidget", "The analog clock widget displays the current time.", None, QtGui.QApplication.UnicodeUTF8))
        self.grossWeightLineEdit.setStyleSheet(_fromUtf8("QLineEdit {background-color: red;}"))
        self.grossWeightLineEdit.setProperty("regexString", QtGui.QApplication.translate("newTicketWidget", "weight", None, QtGui.QApplication.UnicodeUTF8))
        self.grossWeightLineEdit.setObjectName(_fromUtf8("grossWeightLineEdit"))
        self.gridLayout_2.addWidget(self.grossWeightLineEdit, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setText(QtGui.QApplication.translate("newTicketWidget", "Tare", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.tareWeightLineEdit = TareWeightLineEdit(self.groupBox)
        self.tareWeightLineEdit.setEnabled(False)
        self.tareWeightLineEdit.setMinimumSize(QtCore.QSize(71, 20))
        self.tareWeightLineEdit.setMaximumSize(QtCore.QSize(71, 20))
        self.tareWeightLineEdit.setToolTip(QtGui.QApplication.translate("newTicketWidget", "Enter tare weight here. Fraction must be .5 or .0.", None, QtGui.QApplication.UnicodeUTF8))
        self.tareWeightLineEdit.setWhatsThis(QtGui.QApplication.translate("newTicketWidget", "The analog clock widget displays the current time.", None, QtGui.QApplication.UnicodeUTF8))
        self.tareWeightLineEdit.setStyleSheet(_fromUtf8(""))
        self.tareWeightLineEdit.setProperty("regexString", QtGui.QApplication.translate("newTicketWidget", "weight", None, QtGui.QApplication.UnicodeUTF8))
        self.tareWeightLineEdit.setObjectName(_fromUtf8("tareWeightLineEdit"))
        self.gridLayout_2.addWidget(self.tareWeightLineEdit, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setText(QtGui.QApplication.translate("newTicketWidget", "Net", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.netWeightLineEdit = NetWeightLineEdit(self.groupBox)
        self.netWeightLineEdit.setMinimumSize(QtCore.QSize(71, 20))
        self.netWeightLineEdit.setMaximumSize(QtCore.QSize(71, 20))
        self.netWeightLineEdit.setToolTip(QtGui.QApplication.translate("newTicketWidget", "Enter net weight here. Fraction must be .5 or .0.", None, QtGui.QApplication.UnicodeUTF8))
        self.netWeightLineEdit.setWhatsThis(QtGui.QApplication.translate("newTicketWidget", "The analog clock widget displays the current time.", None, QtGui.QApplication.UnicodeUTF8))
        self.netWeightLineEdit.setStyleSheet(_fromUtf8("QLineEdit {background-color: red;}"))
        self.netWeightLineEdit.setProperty("regexString", QtGui.QApplication.translate("newTicketWidget", "weight", None, QtGui.QApplication.UnicodeUTF8))
        self.netWeightLineEdit.setObjectName(_fromUtf8("netWeightLineEdit"))
        self.gridLayout_2.addWidget(self.netWeightLineEdit, 2, 1, 1, 1)
        self.materialCombobox = MaterialCombobox(self.groupBox)
        self.materialCombobox.setToolTip(QtGui.QApplication.translate("newTicketWidget", "Select material type. Vehicle entry opens new dialog.", None, QtGui.QApplication.UnicodeUTF8))
        self.materialCombobox.setWhatsThis(QtGui.QApplication.translate("newTicketWidget", "The analog clock widget displays the current time.", None, QtGui.QApplication.UnicodeUTF8))
        self.materialCombobox.setObjectName(_fromUtf8("materialCombobox"))
        self.gridLayout_2.addWidget(self.materialCombobox, 2, 2, 1, 1)
        self.payloadValueLineEdit = PayloadValueLineEdit(self.groupBox)
        self.payloadValueLineEdit.setMinimumSize(QtCore.QSize(81, 25))
        self.payloadValueLineEdit.setMaximumSize(QtCore.QSize(81, 25))
        self.payloadValueLineEdit.setToolTip(QtGui.QApplication.translate("newTicketWidget", "Total value for this payload in GBP.", None, QtGui.QApplication.UnicodeUTF8))
        self.payloadValueLineEdit.setWhatsThis(QtGui.QApplication.translate("newTicketWidget", "The analog clock widget displays the current time.", None, QtGui.QApplication.UnicodeUTF8))
        self.payloadValueLineEdit.setReadOnly(True)
        self.payloadValueLineEdit.setProperty("regexString", QtGui.QApplication.translate("newTicketWidget", "value", None, QtGui.QApplication.UnicodeUTF8))
        self.payloadValueLineEdit.setObjectName(_fromUtf8("payloadValueLineEdit"))
        self.gridLayout_2.addWidget(self.payloadValueLineEdit, 2, 3, 1, 1)
        self.manualPriceCheckbox = QtGui.QCheckBox(self.groupBox)
        self.manualPriceCheckbox.setMinimumSize(QtCore.QSize(91, 0))
        self.manualPriceCheckbox.setToolTip(QtGui.QApplication.translate("newTicketWidget", "Check to allow manual entry of price.", None, QtGui.QApplication.UnicodeUTF8))
        self.manualPriceCheckbox.setText(QtGui.QApplication.translate("newTicketWidget", "Manual price", None, QtGui.QApplication.UnicodeUTF8))
        self.manualPriceCheckbox.setObjectName(_fromUtf8("manualPriceCheckbox"))
        self.gridLayout_2.addWidget(self.manualPriceCheckbox, 2, 4, 1, 1)
        self.addPayloadButton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addPayloadButton.sizePolicy().hasHeightForWidth())
        self.addPayloadButton.setSizePolicy(sizePolicy)
        self.addPayloadButton.setMinimumSize(QtCore.QSize(81, 0))
        self.addPayloadButton.setText(QtGui.QApplication.translate("newTicketWidget", "Add payload", None, QtGui.QApplication.UnicodeUTF8))
        self.addPayloadButton.setObjectName(_fromUtf8("addPayloadButton"))
        self.gridLayout_2.addWidget(self.addPayloadButton, 3, 0, 1, 5)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.payloadTableWidget = PayloadTableWidget(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.payloadTableWidget.sizePolicy().hasHeightForWidth())
        self.payloadTableWidget.setSizePolicy(sizePolicy)
        self.payloadTableWidget.setMinimumSize(QtCore.QSize(0, 311))
        self.payloadTableWidget.setMaximumSize(QtCore.QSize(8000, 678))
        self.payloadTableWidget.setToolTip(QtGui.QApplication.translate("newTicketWidget", "Double-click blue vehicle text to view/edit vehicle details.\n"
"Click the red \'Delete\' to remove.", None, QtGui.QApplication.UnicodeUTF8))
        self.payloadTableWidget.setWhatsThis(QtGui.QApplication.translate("newTicketWidget", "Extra functions for paylod widget.", None, QtGui.QApplication.UnicodeUTF8))
        self.payloadTableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.payloadTableWidget.setTabKeyNavigation(True)
        self.payloadTableWidget.setProperty("showDropIndicator", False)
        self.payloadTableWidget.setDragDropOverwriteMode(False)
        self.payloadTableWidget.setRowCount(0)
        self.payloadTableWidget.setColumnCount(4)
        self.payloadTableWidget.setObjectName(_fromUtf8("payloadTableWidget"))
        self.payloadTableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.payloadTableWidget.horizontalHeader().setMinimumSectionSize(25)
        self.payloadTableWidget.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.payloadTableWidget)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.reviewTicketButton = QtGui.QCommandLinkButton(self.groupBox)
        self.reviewTicketButton.setEnabled(False)
        self.reviewTicketButton.setMinimumSize(QtCore.QSize(131, 0))
        self.reviewTicketButton.setMaximumSize(QtCore.QSize(131, 16777215))
        self.reviewTicketButton.setText(QtGui.QApplication.translate("newTicketWidget", "Review ticket", None, QtGui.QApplication.UnicodeUTF8))
        self.reviewTicketButton.setObjectName(_fromUtf8("reviewTicketButton"))
        self.gridLayout_3.addWidget(self.reviewTicketButton, 0, 0, 1, 1)
        self.totalValueLabel = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.totalValueLabel.setFont(font)
        self.totalValueLabel.setText(QtGui.QApplication.translate("newTicketWidget", "Total", None, QtGui.QApplication.UnicodeUTF8))
        self.totalValueLabel.setObjectName(_fromUtf8("totalValueLabel"))
        self.gridLayout_3.addWidget(self.totalValueLabel, 0, 1, 1, 1)
        self.totalValueLineEdit = TotalValueLineEdit(self.groupBox)
        self.totalValueLineEdit.setMinimumSize(QtCore.QSize(101, 25))
        self.totalValueLineEdit.setMaximumSize(QtCore.QSize(101, 25))
        self.totalValueLineEdit.setToolTip(QtGui.QApplication.translate("newTicketWidget", "Total to pay customer in GBP.", None, QtGui.QApplication.UnicodeUTF8))
        self.totalValueLineEdit.setWhatsThis(QtGui.QApplication.translate("newTicketWidget", "The analog clock widget displays the current time.", None, QtGui.QApplication.UnicodeUTF8))
        self.totalValueLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.totalValueLineEdit.setReadOnly(True)
        self.totalValueLineEdit.setObjectName(_fromUtf8("totalValueLineEdit"))
        self.gridLayout_3.addWidget(self.totalValueLineEdit, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.horizontalLayout.addWidget(self.groupBox)

        self.retranslateUi(newTicketWidget)
        QtCore.QObject.connect(self.firstNameLineEdit, QtCore.SIGNAL(_fromUtf8("textEdited(QString)")), self.firstNameLineEdit.onTextEdited)
        QtCore.QObject.connect(self.firstNameLineEdit, QtCore.SIGNAL(_fromUtf8("valid()")), self.firstNameLineEdit.onValid)
        QtCore.QObject.connect(self.firstNameLineEdit, QtCore.SIGNAL(_fromUtf8("invalid()")), self.firstNameLineEdit.onInvalid)
        QtCore.QObject.connect(self.firstNameLineEdit, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), newTicketWidget.update)
        QtCore.QObject.connect(self.grossWeightLineEdit, QtCore.SIGNAL(_fromUtf8("textEdited(QString)")), self.grossWeightLineEdit.onTextEdited)
        QtCore.QObject.connect(self.grossWeightLineEdit, QtCore.SIGNAL(_fromUtf8("enableNetWeight()")), self.netWeightLineEdit.onEnableNetWeight)
        QtCore.QObject.connect(self.grossWeightLineEdit, QtCore.SIGNAL(_fromUtf8("disableNetWeight()")), self.netWeightLineEdit.onDisableNetWeight)
        QtCore.QObject.connect(self.grossWeightLineEdit, QtCore.SIGNAL(_fromUtf8("enableTareWeight()")), self.tareWeightLineEdit.onEnableTareWeight)
        QtCore.QObject.connect(self.grossWeightLineEdit, QtCore.SIGNAL(_fromUtf8("disableTareWeight()")), self.tareWeightLineEdit.onDisableTareWeight)
        QtCore.QObject.connect(self.grossWeightLineEdit, QtCore.SIGNAL(_fromUtf8("valid()")), self.grossWeightLineEdit.onValid)
        QtCore.QObject.connect(self.grossWeightLineEdit, QtCore.SIGNAL(_fromUtf8("invalid()")), self.grossWeightLineEdit.onInvalid)
        QtCore.QObject.connect(self.grossWeightLineEdit, QtCore.SIGNAL(_fromUtf8("grossWeightValue(QString)")), self.tareWeightLineEdit.onGrossWeightValue)
        QtCore.QObject.connect(self.grossWeightLineEdit, QtCore.SIGNAL(_fromUtf8("clearNetWeight()")), self.netWeightLineEdit.onClearNetWeight)
        QtCore.QObject.connect(self.grossWeightLineEdit, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), newTicketWidget.update)
        QtCore.QObject.connect(self.houseNumberLineEdit, QtCore.SIGNAL(_fromUtf8("textEdited(QString)")), self.houseNumberLineEdit.onTextEdited)
        QtCore.QObject.connect(self.houseNumberLineEdit, QtCore.SIGNAL(_fromUtf8("valid()")), self.houseNumberLineEdit.onValid)
        QtCore.QObject.connect(self.houseNumberLineEdit, QtCore.SIGNAL(_fromUtf8("invalid()")), self.houseNumberLineEdit.onInvalid)
        QtCore.QObject.connect(self.houseNumberLineEdit, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), newTicketWidget.update)
        QtCore.QObject.connect(self.lastNameLineEdit, QtCore.SIGNAL(_fromUtf8("textEdited(QString)")), self.lastNameLineEdit.onTextEdited)
        QtCore.QObject.connect(self.lastNameLineEdit, QtCore.SIGNAL(_fromUtf8("valid()")), self.lastNameLineEdit.onValid)
        QtCore.QObject.connect(self.lastNameLineEdit, QtCore.SIGNAL(_fromUtf8("invalid()")), self.lastNameLineEdit.onInvalid)
        QtCore.QObject.connect(self.lastNameLineEdit, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), newTicketWidget.update)
        QtCore.QObject.connect(self.manualPriceCheckbox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.payloadValueLineEdit.setReadOnlyInverted)
        QtCore.QObject.connect(self.materialCombobox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), newTicketWidget.update)
        QtCore.QObject.connect(self.materialCombobox, QtCore.SIGNAL(_fromUtf8("materialChanged(QString)")), self.netWeightLineEdit.onMaterialChanged)
        QtCore.QObject.connect(self.materialCombobox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), self.materialCombobox.onIndexChange)
        QtCore.QObject.connect(self.netWeightLineEdit, QtCore.SIGNAL(_fromUtf8("textEdited(QString)")), self.netWeightLineEdit.onTextEdited)
        QtCore.QObject.connect(self.netWeightLineEdit, QtCore.SIGNAL(_fromUtf8("valid()")), self.netWeightLineEdit.onValid)
        QtCore.QObject.connect(self.netWeightLineEdit, QtCore.SIGNAL(_fromUtf8("invalid()")), self.netWeightLineEdit.onInvalid)
        QtCore.QObject.connect(self.netWeightLineEdit, QtCore.SIGNAL(_fromUtf8("enableGrossWeight()")), self.grossWeightLineEdit.onEnableGrossWeight)
        QtCore.QObject.connect(self.netWeightLineEdit, QtCore.SIGNAL(_fromUtf8("disableGrossWeight()")), self.grossWeightLineEdit.onDisableGrossWeight)
        QtCore.QObject.connect(self.netWeightLineEdit, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), newTicketWidget.update)
        QtCore.QObject.connect(self.netWeightLineEdit, QtCore.SIGNAL(_fromUtf8("calculatePayloadValue(QString,QString)")), self.payloadValueLineEdit.onCalculatePayloadValue)
        QtCore.QObject.connect(self.netWeightLineEdit, QtCore.SIGNAL(_fromUtf8("clearPayloadValue()")), self.payloadValueLineEdit.onClearPayloadValue)
        QtCore.QObject.connect(self.payloadTableWidget, QtCore.SIGNAL(_fromUtf8("cellChanged(int,int)")), self.payloadTableWidget.onChange)
        QtCore.QObject.connect(self.payloadTableWidget, QtCore.SIGNAL(_fromUtf8("calculateTotalValue(PyQt_PyObject)")), self.totalValueLineEdit.onCalculateTotalValue)
        QtCore.QObject.connect(self.payloadTableWidget, QtCore.SIGNAL(_fromUtf8("cellChanged(int,int)")), newTicketWidget.update)
        QtCore.QObject.connect(self.payloadValueLineEdit, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), newTicketWidget.update)
        QtCore.QObject.connect(self.payloadValueLineEdit, QtCore.SIGNAL(_fromUtf8("textEdited(QString)")), self.payloadValueLineEdit.onTextEdited)
        QtCore.QObject.connect(self.payloadValueLineEdit, QtCore.SIGNAL(_fromUtf8("valid()")), self.payloadValueLineEdit.onValid)
        QtCore.QObject.connect(self.payloadValueLineEdit, QtCore.SIGNAL(_fromUtf8("invalid()")), self.payloadValueLineEdit.onInvalid)
        QtCore.QObject.connect(self.postcodeLineEdit, QtCore.SIGNAL(_fromUtf8("textEdited(QString)")), self.postcodeLineEdit.onTextEdited)
        QtCore.QObject.connect(self.postcodeLineEdit, QtCore.SIGNAL(_fromUtf8("valid()")), self.postcodeLineEdit.onValid)
        QtCore.QObject.connect(self.postcodeLineEdit, QtCore.SIGNAL(_fromUtf8("invalid()")), self.postcodeLineEdit.onInvalid)
        QtCore.QObject.connect(self.postcodeLineEdit, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), newTicketWidget.update)
        QtCore.QObject.connect(self.streetLineEdit, QtCore.SIGNAL(_fromUtf8("textEdited(QString)")), self.streetLineEdit.onTextEdited)
        QtCore.QObject.connect(self.streetLineEdit, QtCore.SIGNAL(_fromUtf8("valid()")), self.streetLineEdit.onValid)
        QtCore.QObject.connect(self.streetLineEdit, QtCore.SIGNAL(_fromUtf8("invalid()")), self.streetLineEdit.onInvalid)
        QtCore.QObject.connect(self.streetLineEdit, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), newTicketWidget.update)
        QtCore.QObject.connect(self.tareWeightLineEdit, QtCore.SIGNAL(_fromUtf8("textEdited(QString)")), self.tareWeightLineEdit.onTextEdited)
        QtCore.QObject.connect(self.tareWeightLineEdit, QtCore.SIGNAL(_fromUtf8("valid()")), self.tareWeightLineEdit.onValid)
        QtCore.QObject.connect(self.tareWeightLineEdit, QtCore.SIGNAL(_fromUtf8("sendGrossWeightValue()")), self.grossWeightLineEdit.onSendGrossWeightValue)
        QtCore.QObject.connect(self.tareWeightLineEdit, QtCore.SIGNAL(_fromUtf8("calculateNetWeight(QString,QString)")), self.netWeightLineEdit.onCalculateNetWeight)
        QtCore.QObject.connect(self.tareWeightLineEdit, QtCore.SIGNAL(_fromUtf8("invalid()")), self.tareWeightLineEdit.onInvalid)
        QtCore.QObject.connect(self.tareWeightLineEdit, QtCore.SIGNAL(_fromUtf8("clearNetWeight()")), self.netWeightLineEdit.onClearNetWeight)
        QtCore.QObject.connect(self.tareWeightLineEdit, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), newTicketWidget.update)
        QtCore.QObject.connect(self.townLineEdit, QtCore.SIGNAL(_fromUtf8("textEdited(QString)")), self.townLineEdit.onTextEdited)
        QtCore.QObject.connect(self.townLineEdit, QtCore.SIGNAL(_fromUtf8("valid()")), self.townLineEdit.onValid)
        QtCore.QObject.connect(self.townLineEdit, QtCore.SIGNAL(_fromUtf8("invalid()")), self.townLineEdit.onInvalid)
        QtCore.QObject.connect(self.townLineEdit, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), newTicketWidget.update)
        QtCore.QObject.connect(self.vehicleRegistrationLineEdit, QtCore.SIGNAL(_fromUtf8("textEdited(QString)")), self.vehicleRegistrationLineEdit.onTextEdited)
        QtCore.QObject.connect(self.vehicleRegistrationLineEdit, QtCore.SIGNAL(_fromUtf8("valid()")), self.vehicleRegistrationLineEdit.onValid)
        QtCore.QObject.connect(self.vehicleRegistrationLineEdit, QtCore.SIGNAL(_fromUtf8("invalid()")), self.vehicleRegistrationLineEdit.onInvalid)
        QtCore.QObject.connect(self.vehicleRegistrationLineEdit, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), newTicketWidget.update)
        QtCore.QMetaObject.connectSlotsByName(newTicketWidget)

    def retranslateUi(self, newTicketWidget):
        pass

from custom_widgets.validatingLineEdit import ValidatingLineEdit
from custom_widgets.tareWeightLineEdit import TareWeightLineEdit
from custom_widgets.grossWeightLineEdit import GrossWeightLineEdit
from custom_widgets.payloadValueLineEdit import PayloadValueLineEdit
from custom_widgets.netWeightLineEdit import NetWeightLineEdit
from custom_widgets.payloadTableWidget import PayloadTableWidget
from custom_widgets.totalValueLineEdit import TotalValueLineEdit
from custom_widgets.materialCombobox import MaterialCombobox
