# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vehicle_dialog_design.ui'
#
# Created: Thu Sep 29 11:45:36 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_vehicleDialog(object):
    def setupUi(self, vehicleDialog):
        vehicleDialog.setObjectName(_fromUtf8("vehicleDialog"))
        vehicleDialog.resize(239, 262)
        vehicleDialog.setWindowTitle(QtGui.QApplication.translate("vehicleDialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout = QtGui.QVBoxLayout(vehicleDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.makeLabel = QtGui.QLabel(vehicleDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.makeLabel.sizePolicy().hasHeightForWidth())
        self.makeLabel.setSizePolicy(sizePolicy)
        self.makeLabel.setMinimumSize(QtCore.QSize(32, 16))
        self.makeLabel.setMaximumSize(QtCore.QSize(32, 16))
        self.makeLabel.setText(QtGui.QApplication.translate("vehicleDialog", "Make", None, QtGui.QApplication.UnicodeUTF8))
        self.makeLabel.setObjectName(_fromUtf8("makeLabel"))
        self.gridLayout.addWidget(self.makeLabel, 0, 0, 1, 1)
        self.makeEdit = ValidatingLineEdit(vehicleDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.makeEdit.sizePolicy().hasHeightForWidth())
        self.makeEdit.setSizePolicy(sizePolicy)
        self.makeEdit.setMinimumSize(QtCore.QSize(161, 25))
        self.makeEdit.setMaximumSize(QtCore.QSize(161, 25))
        self.makeEdit.setToolTip(QtGui.QApplication.translate("vehicleDialog", "Enter vehicle make.", None, QtGui.QApplication.UnicodeUTF8))
        self.makeEdit.setWhatsThis(QtGui.QApplication.translate("vehicleDialog", "The analog clock widget displays the current time.", None, QtGui.QApplication.UnicodeUTF8))
        self.makeEdit.setStyleSheet(_fromUtf8(""))
        self.makeEdit.setProperty("regexString", QtGui.QApplication.translate("vehicleDialog", "street", None, QtGui.QApplication.UnicodeUTF8))
        self.makeEdit.setObjectName(_fromUtf8("makeEdit"))
        self.gridLayout.addWidget(self.makeEdit, 0, 1, 1, 2)
        self.modelLabel = QtGui.QLabel(vehicleDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modelLabel.sizePolicy().hasHeightForWidth())
        self.modelLabel.setSizePolicy(sizePolicy)
        self.modelLabel.setMinimumSize(QtCore.QSize(36, 16))
        self.modelLabel.setMaximumSize(QtCore.QSize(36, 16))
        self.modelLabel.setText(QtGui.QApplication.translate("vehicleDialog", "Model", None, QtGui.QApplication.UnicodeUTF8))
        self.modelLabel.setObjectName(_fromUtf8("modelLabel"))
        self.gridLayout.addWidget(self.modelLabel, 1, 0, 1, 1)
        self.modelEdit = ValidatingLineEdit(vehicleDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modelEdit.sizePolicy().hasHeightForWidth())
        self.modelEdit.setSizePolicy(sizePolicy)
        self.modelEdit.setMinimumSize(QtCore.QSize(161, 25))
        self.modelEdit.setMaximumSize(QtCore.QSize(161, 25))
        self.modelEdit.setToolTip(QtGui.QApplication.translate("vehicleDialog", "Enter vehicle model.", None, QtGui.QApplication.UnicodeUTF8))
        self.modelEdit.setWhatsThis(QtGui.QApplication.translate("vehicleDialog", "The analog clock widget displays the current time.", None, QtGui.QApplication.UnicodeUTF8))
        self.modelEdit.setStyleSheet(_fromUtf8(""))
        self.modelEdit.setProperty("regexString", QtGui.QApplication.translate("vehicleDialog", "model", None, QtGui.QApplication.UnicodeUTF8))
        self.modelEdit.setObjectName(_fromUtf8("modelEdit"))
        self.gridLayout.addWidget(self.modelEdit, 1, 1, 1, 2)
        self.colourLabel = QtGui.QLabel(vehicleDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colourLabel.sizePolicy().hasHeightForWidth())
        self.colourLabel.setSizePolicy(sizePolicy)
        self.colourLabel.setMinimumSize(QtCore.QSize(39, 16))
        self.colourLabel.setMaximumSize(QtCore.QSize(39, 16))
        self.colourLabel.setText(QtGui.QApplication.translate("vehicleDialog", "Colour", None, QtGui.QApplication.UnicodeUTF8))
        self.colourLabel.setObjectName(_fromUtf8("colourLabel"))
        self.gridLayout.addWidget(self.colourLabel, 2, 0, 1, 1)
        self.colourCombobox = QtGui.QComboBox(vehicleDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colourCombobox.sizePolicy().hasHeightForWidth())
        self.colourCombobox.setSizePolicy(sizePolicy)
        self.colourCombobox.setMinimumSize(QtCore.QSize(121, 25))
        self.colourCombobox.setMaximumSize(QtCore.QSize(121, 25))
        self.colourCombobox.setToolTip(QtGui.QApplication.translate("vehicleDialog", "Select vehicle colour.", None, QtGui.QApplication.UnicodeUTF8))
        self.colourCombobox.setObjectName(_fromUtf8("colourCombobox"))
        self.colourCombobox.addItem(_fromUtf8(""))
        self.colourCombobox.setItemText(0, QtGui.QApplication.translate("vehicleDialog", "Black", None, QtGui.QApplication.UnicodeUTF8))
        self.colourCombobox.addItem(_fromUtf8(""))
        self.colourCombobox.setItemText(1, QtGui.QApplication.translate("vehicleDialog", "Blue", None, QtGui.QApplication.UnicodeUTF8))
        self.colourCombobox.addItem(_fromUtf8(""))
        self.colourCombobox.setItemText(2, QtGui.QApplication.translate("vehicleDialog", "Brown", None, QtGui.QApplication.UnicodeUTF8))
        self.colourCombobox.addItem(_fromUtf8(""))
        self.colourCombobox.setItemText(3, QtGui.QApplication.translate("vehicleDialog", "Green", None, QtGui.QApplication.UnicodeUTF8))
        self.colourCombobox.addItem(_fromUtf8(""))
        self.colourCombobox.setItemText(4, QtGui.QApplication.translate("vehicleDialog", "Grey", None, QtGui.QApplication.UnicodeUTF8))
        self.colourCombobox.addItem(_fromUtf8(""))
        self.colourCombobox.setItemText(5, QtGui.QApplication.translate("vehicleDialog", "Orange", None, QtGui.QApplication.UnicodeUTF8))
        self.colourCombobox.addItem(_fromUtf8(""))
        self.colourCombobox.setItemText(6, QtGui.QApplication.translate("vehicleDialog", "Pink", None, QtGui.QApplication.UnicodeUTF8))
        self.colourCombobox.addItem(_fromUtf8(""))
        self.colourCombobox.setItemText(7, QtGui.QApplication.translate("vehicleDialog", "Purple", None, QtGui.QApplication.UnicodeUTF8))
        self.colourCombobox.addItem(_fromUtf8(""))
        self.colourCombobox.setItemText(8, QtGui.QApplication.translate("vehicleDialog", "Red", None, QtGui.QApplication.UnicodeUTF8))
        self.colourCombobox.addItem(_fromUtf8(""))
        self.colourCombobox.setItemText(9, QtGui.QApplication.translate("vehicleDialog", "White", None, QtGui.QApplication.UnicodeUTF8))
        self.colourCombobox.addItem(_fromUtf8(""))
        self.colourCombobox.setItemText(10, QtGui.QApplication.translate("vehicleDialog", "Yellow", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLayout.addWidget(self.colourCombobox, 2, 1, 1, 2)
        self.vehicleRegistrationLabel = QtGui.QLabel(vehicleDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vehicleRegistrationLabel.sizePolicy().hasHeightForWidth())
        self.vehicleRegistrationLabel.setSizePolicy(sizePolicy)
        self.vehicleRegistrationLabel.setMinimumSize(QtCore.QSize(71, 16))
        self.vehicleRegistrationLabel.setMaximumSize(QtCore.QSize(71, 16))
        self.vehicleRegistrationLabel.setText(QtGui.QApplication.translate("vehicleDialog", "Registration", None, QtGui.QApplication.UnicodeUTF8))
        self.vehicleRegistrationLabel.setObjectName(_fromUtf8("vehicleRegistrationLabel"))
        self.gridLayout.addWidget(self.vehicleRegistrationLabel, 3, 0, 1, 2)
        self.vehicleRegistrationEdit = ValidatingLineEdit(vehicleDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vehicleRegistrationEdit.sizePolicy().hasHeightForWidth())
        self.vehicleRegistrationEdit.setSizePolicy(sizePolicy)
        self.vehicleRegistrationEdit.setMinimumSize(QtCore.QSize(91, 25))
        self.vehicleRegistrationEdit.setMaximumSize(QtCore.QSize(91, 25))
        self.vehicleRegistrationEdit.setToolTip(QtGui.QApplication.translate("vehicleDialog", "Enter valid UK vehicle registration number.", None, QtGui.QApplication.UnicodeUTF8))
        self.vehicleRegistrationEdit.setWhatsThis(QtGui.QApplication.translate("vehicleDialog", "The analog clock widget displays the current time.", None, QtGui.QApplication.UnicodeUTF8))
        self.vehicleRegistrationEdit.setStyleSheet(_fromUtf8(""))
        self.vehicleRegistrationEdit.setProperty("regexString", QtGui.QApplication.translate("vehicleDialog", "post2001Reg", None, QtGui.QApplication.UnicodeUTF8))
        self.vehicleRegistrationEdit.setObjectName(_fromUtf8("vehicleRegistrationEdit"))
        self.gridLayout.addWidget(self.vehicleRegistrationEdit, 3, 2, 1, 1)
        self.vinLabel = QtGui.QLabel(vehicleDialog)
        self.vinLabel.setMaximumSize(QtCore.QSize(21, 16))
        self.vinLabel.setText(QtGui.QApplication.translate("vehicleDialog", "VIN", None, QtGui.QApplication.UnicodeUTF8))
        self.vinLabel.setObjectName(_fromUtf8("vinLabel"))
        self.gridLayout.addWidget(self.vinLabel, 4, 0, 1, 1)
        self.vinEdit = ValidatingLineEdit(vehicleDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vinEdit.sizePolicy().hasHeightForWidth())
        self.vinEdit.setSizePolicy(sizePolicy)
        self.vinEdit.setMinimumSize(QtCore.QSize(0, 25))
        self.vinEdit.setMaximumSize(QtCore.QSize(183, 25))
        self.vinEdit.setToolTip(QtGui.QApplication.translate("vehicleDialog", "Enter valid VIN number.", None, QtGui.QApplication.UnicodeUTF8))
        self.vinEdit.setWhatsThis(QtGui.QApplication.translate("vehicleDialog", "The analog clock widget displays the current time.", None, QtGui.QApplication.UnicodeUTF8))
        self.vinEdit.setStyleSheet(_fromUtf8(""))
        self.vinEdit.setProperty("regexString", QtGui.QApplication.translate("vehicleDialog", "vin", None, QtGui.QApplication.UnicodeUTF8))
        self.vinEdit.setObjectName(_fromUtf8("vinEdit"))
        self.gridLayout.addWidget(self.vinEdit, 4, 1, 1, 2)
        self.idLabel = QtGui.QLabel(vehicleDialog)
        self.idLabel.setMinimumSize(QtCore.QSize(16, 16))
        self.idLabel.setMaximumSize(QtCore.QSize(16, 16))
        self.idLabel.setText(QtGui.QApplication.translate("vehicleDialog", "ID", None, QtGui.QApplication.UnicodeUTF8))
        self.idLabel.setObjectName(_fromUtf8("idLabel"))
        self.gridLayout.addWidget(self.idLabel, 5, 0, 1, 1)
        self.idCombobox = QtGui.QComboBox(vehicleDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.idCombobox.sizePolicy().hasHeightForWidth())
        self.idCombobox.setSizePolicy(sizePolicy)
        self.idCombobox.setMinimumSize(QtCore.QSize(121, 25))
        self.idCombobox.setMaximumSize(QtCore.QSize(121, 25))
        self.idCombobox.setToolTip(QtGui.QApplication.translate("vehicleDialog", "Select ID status.", None, QtGui.QApplication.UnicodeUTF8))
        self.idCombobox.setObjectName(_fromUtf8("idCombobox"))
        self.idCombobox.addItem(_fromUtf8(""))
        self.idCombobox.setItemText(0, QtGui.QApplication.translate("vehicleDialog", "Checked", None, QtGui.QApplication.UnicodeUTF8))
        self.idCombobox.addItem(_fromUtf8(""))
        self.idCombobox.setItemText(1, QtGui.QApplication.translate("vehicleDialog", "Known", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLayout.addWidget(self.idCombobox, 5, 1, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.cancelButton = QtGui.QPushButton(vehicleDialog)
        self.cancelButton.setText(QtGui.QApplication.translate("vehicleDialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setObjectName(_fromUtf8("cancelButton"))
        self.horizontalLayout.addWidget(self.cancelButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.acceptButton = QtGui.QPushButton(vehicleDialog)
        self.acceptButton.setText(QtGui.QApplication.translate("vehicleDialog", "Accept", None, QtGui.QApplication.UnicodeUTF8))
        self.acceptButton.setObjectName(_fromUtf8("acceptButton"))
        self.horizontalLayout.addWidget(self.acceptButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(vehicleDialog)
        QtCore.QMetaObject.connectSlotsByName(vehicleDialog)

    def retranslateUi(self, vehicleDialog):
        pass

from custom_widgets.validatingLineEdit import ValidatingLineEdit
