# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_ticket_dialog_design.ui'
#
# Created: Thu May 26 13:51:39 2011
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_newTicketDialog(object):
    def setupUi(self, newTicketDialog):
        newTicketDialog.setObjectName(_fromUtf8("newTicketDialog"))
        newTicketDialog.resize(386, 574)
        self.verticalLayout = QtGui.QVBoxLayout(newTicketDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.newTicketTabWidget = QtGui.QTabWidget(newTicketDialog)
        self.newTicketTabWidget.setMinimumSize(QtCore.QSize(0, 431))
        self.newTicketTabWidget.setObjectName(_fromUtf8("newTicketTabWidget"))
        self.customerTab = QtGui.QWidget()
        self.customerTab.setObjectName(_fromUtf8("customerTab"))
        self.layoutWidget = QtGui.QWidget(self.customerTab)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 11, 182, 152))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.nameLabel = QtGui.QLabel(self.layoutWidget)
        self.nameLabel.setObjectName(_fromUtf8("nameLabel"))
        self.gridLayout.addWidget(self.nameLabel, 0, 0, 1, 1)
        self.nameLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.nameLineEdit.setObjectName(_fromUtf8("nameLineEdit"))
        self.gridLayout.addWidget(self.nameLineEdit, 0, 1, 1, 2)
        self.houseNumberLabel = QtGui.QLabel(self.layoutWidget)
        self.houseNumberLabel.setObjectName(_fromUtf8("houseNumberLabel"))
        self.gridLayout.addWidget(self.houseNumberLabel, 1, 0, 1, 1)
        self.houseNumberLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.houseNumberLineEdit.setMinimumSize(QtCore.QSize(51, 0))
        self.houseNumberLineEdit.setMaximumSize(QtCore.QSize(51, 16777215))
        self.houseNumberLineEdit.setObjectName(_fromUtf8("houseNumberLineEdit"))
        self.gridLayout.addWidget(self.houseNumberLineEdit, 1, 1, 1, 2)
        self.streetLabel = QtGui.QLabel(self.layoutWidget)
        self.streetLabel.setObjectName(_fromUtf8("streetLabel"))
        self.gridLayout.addWidget(self.streetLabel, 2, 0, 1, 1)
        self.streetLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.streetLineEdit.setMaximumSize(QtCore.QSize(133, 16777215))
        self.streetLineEdit.setObjectName(_fromUtf8("streetLineEdit"))
        self.gridLayout.addWidget(self.streetLineEdit, 2, 1, 1, 2)
        self.townLabel = QtGui.QLabel(self.layoutWidget)
        self.townLabel.setObjectName(_fromUtf8("townLabel"))
        self.gridLayout.addWidget(self.townLabel, 3, 0, 1, 1)
        self.townLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.townLineEdit.setMaximumSize(QtCore.QSize(133, 16777215))
        self.townLineEdit.setObjectName(_fromUtf8("townLineEdit"))
        self.gridLayout.addWidget(self.townLineEdit, 3, 1, 1, 2)
        self.postcodeLabel = QtGui.QLabel(self.layoutWidget)
        self.postcodeLabel.setObjectName(_fromUtf8("postcodeLabel"))
        self.gridLayout.addWidget(self.postcodeLabel, 4, 0, 1, 1)
        self.postcodeLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.postcodeLineEdit.setMinimumSize(QtCore.QSize(81, 0))
        self.postcodeLineEdit.setMaximumSize(QtCore.QSize(81, 16777215))
        self.postcodeLineEdit.setObjectName(_fromUtf8("postcodeLineEdit"))
        self.gridLayout.addWidget(self.postcodeLineEdit, 4, 1, 1, 2)
        self.vehicleRegistrationLabel = QtGui.QLabel(self.layoutWidget)
        self.vehicleRegistrationLabel.setObjectName(_fromUtf8("vehicleRegistrationLabel"))
        self.gridLayout.addWidget(self.vehicleRegistrationLabel, 5, 0, 1, 2)
        self.vehicleRegistrationLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.vehicleRegistrationLineEdit.setMinimumSize(QtCore.QSize(81, 0))
        self.vehicleRegistrationLineEdit.setMaximumSize(QtCore.QSize(81, 16777215))
        self.vehicleRegistrationLineEdit.setObjectName(_fromUtf8("vehicleRegistrationLineEdit"))
        self.gridLayout.addWidget(self.vehicleRegistrationLineEdit, 5, 2, 1, 1)
        self.newTicketTabWidget.addTab(self.customerTab, _fromUtf8(""))
        self.payloadTab = QtGui.QWidget()
        self.payloadTab.setObjectName(_fromUtf8("payloadTab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.payloadTab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.grossWeightLineEdit = QtGui.QLineEdit(self.payloadTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grossWeightLineEdit.sizePolicy().hasHeightForWidth())
        self.grossWeightLineEdit.setSizePolicy(sizePolicy)
        self.grossWeightLineEdit.setMinimumSize(QtCore.QSize(71, 0))
        self.grossWeightLineEdit.setMaximumSize(QtCore.QSize(71, 16777215))
        self.grossWeightLineEdit.setObjectName(_fromUtf8("grossWeightLineEdit"))
        self.gridLayout_2.addWidget(self.grossWeightLineEdit, 0, 0, 1, 1)
        self.tareWeightLineEdit = QtGui.QLineEdit(self.payloadTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tareWeightLineEdit.sizePolicy().hasHeightForWidth())
        self.tareWeightLineEdit.setSizePolicy(sizePolicy)
        self.tareWeightLineEdit.setMinimumSize(QtCore.QSize(71, 0))
        self.tareWeightLineEdit.setMaximumSize(QtCore.QSize(71, 16777215))
        self.tareWeightLineEdit.setObjectName(_fromUtf8("tareWeightLineEdit"))
        self.gridLayout_2.addWidget(self.tareWeightLineEdit, 1, 0, 1, 1)
        self.netWeightLineEdit = QtGui.QLineEdit(self.payloadTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.netWeightLineEdit.sizePolicy().hasHeightForWidth())
        self.netWeightLineEdit.setSizePolicy(sizePolicy)
        self.netWeightLineEdit.setMinimumSize(QtCore.QSize(71, 0))
        self.netWeightLineEdit.setMaximumSize(QtCore.QSize(71, 16777215))
        self.netWeightLineEdit.setObjectName(_fromUtf8("netWeightLineEdit"))
        self.gridLayout_2.addWidget(self.netWeightLineEdit, 2, 0, 1, 1)
        self.materialCombobox = QtGui.QComboBox(self.payloadTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.materialCombobox.sizePolicy().hasHeightForWidth())
        self.materialCombobox.setSizePolicy(sizePolicy)
        self.materialCombobox.setMinimumSize(QtCore.QSize(91, 0))
        self.materialCombobox.setMaximumSize(QtCore.QSize(91, 16777215))
        self.materialCombobox.setObjectName(_fromUtf8("materialCombobox"))
        self.materialCombobox.addItem(_fromUtf8(""))
        self.materialCombobox.addItem(_fromUtf8(""))
        self.materialCombobox.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.materialCombobox, 2, 1, 1, 1)
        self.payloadValueLineEdit = QtGui.QLineEdit(self.payloadTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.payloadValueLineEdit.sizePolicy().hasHeightForWidth())
        self.payloadValueLineEdit.setSizePolicy(sizePolicy)
        self.payloadValueLineEdit.setMinimumSize(QtCore.QSize(71, 0))
        self.payloadValueLineEdit.setMaximumSize(QtCore.QSize(71, 16777215))
        self.payloadValueLineEdit.setReadOnly(True)
        self.payloadValueLineEdit.setObjectName(_fromUtf8("payloadValueLineEdit"))
        self.gridLayout_2.addWidget(self.payloadValueLineEdit, 2, 2, 1, 2)
        self.manualPriceCheckbox = QtGui.QCheckBox(self.payloadTab)
        self.manualPriceCheckbox.setMinimumSize(QtCore.QSize(91, 0))
        self.manualPriceCheckbox.setObjectName(_fromUtf8("manualPriceCheckbox"))
        self.gridLayout_2.addWidget(self.manualPriceCheckbox, 2, 4, 1, 1)
        self.addPayloadButton = QtGui.QPushButton(self.payloadTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addPayloadButton.sizePolicy().hasHeightForWidth())
        self.addPayloadButton.setSizePolicy(sizePolicy)
        self.addPayloadButton.setMinimumSize(QtCore.QSize(81, 0))
        self.addPayloadButton.setObjectName(_fromUtf8("addPayloadButton"))
        self.gridLayout_2.addWidget(self.addPayloadButton, 3, 4, 1, 1)
        self.payloadTableWidget = QtGui.QTableWidget(self.payloadTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.payloadTableWidget.sizePolicy().hasHeightForWidth())
        self.payloadTableWidget.setSizePolicy(sizePolicy)
        self.payloadTableWidget.setMinimumSize(QtCore.QSize(341, 0))
        self.payloadTableWidget.setMaximumSize(QtCore.QSize(341, 16777215))
        self.payloadTableWidget.setRowCount(12)
        self.payloadTableWidget.setColumnCount(3)
        self.payloadTableWidget.setObjectName(_fromUtf8("payloadTableWidget"))
        self.payloadTableWidget.setColumnCount(3)
        self.payloadTableWidget.setRowCount(12)
        self.payloadTableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.payloadTableWidget.horizontalHeader().setMinimumSectionSize(25)
        self.gridLayout_2.addWidget(self.payloadTableWidget, 4, 0, 1, 5)
        self.totalValueLabel = QtGui.QLabel(self.payloadTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.totalValueLabel.setFont(font)
        self.totalValueLabel.setObjectName(_fromUtf8("totalValueLabel"))
        self.gridLayout_2.addWidget(self.totalValueLabel, 5, 2, 1, 1)
        self.totalValueLineEdit = QtGui.QLineEdit(self.payloadTab)
        self.totalValueLineEdit.setMinimumSize(QtCore.QSize(101, 0))
        self.totalValueLineEdit.setMaximumSize(QtCore.QSize(101, 16777215))
        self.totalValueLineEdit.setObjectName(_fromUtf8("totalValueLineEdit"))
        self.gridLayout_2.addWidget(self.totalValueLineEdit, 5, 3, 1, 2)
        self.reviewTicketButton = QtGui.QCommandLinkButton(self.payloadTab)
        self.reviewTicketButton.setMinimumSize(QtCore.QSize(131, 0))
        self.reviewTicketButton.setMaximumSize(QtCore.QSize(131, 16777215))
        self.reviewTicketButton.setObjectName(_fromUtf8("reviewTicketButton"))
        self.gridLayout_2.addWidget(self.reviewTicketButton, 6, 2, 1, 3)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.newTicketTabWidget.addTab(self.payloadTab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.newTicketTabWidget)
        self.nameLabel.setBuddy(self.nameLineEdit)
        self.houseNumberLabel.setBuddy(self.houseNumberLineEdit)
        self.streetLabel.setBuddy(self.streetLineEdit)
        self.townLabel.setBuddy(self.townLineEdit)
        self.postcodeLabel.setBuddy(self.postcodeLineEdit)
        self.vehicleRegistrationLabel.setBuddy(self.vehicleRegistrationLineEdit)
        self.totalValueLabel.setBuddy(self.totalValueLineEdit)

        self.retranslateUi(newTicketDialog)
        self.newTicketTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(newTicketDialog)

    def retranslateUi(self, newTicketDialog):
        newTicketDialog.setWindowTitle(QtGui.QApplication.translate("newTicketDialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.nameLabel.setText(QtGui.QApplication.translate("newTicketDialog", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.houseNumberLabel.setText(QtGui.QApplication.translate("newTicketDialog", "House number", None, QtGui.QApplication.UnicodeUTF8))
        self.streetLabel.setText(QtGui.QApplication.translate("newTicketDialog", "Street", None, QtGui.QApplication.UnicodeUTF8))
        self.townLabel.setText(QtGui.QApplication.translate("newTicketDialog", "Town", None, QtGui.QApplication.UnicodeUTF8))
        self.postcodeLabel.setText(QtGui.QApplication.translate("newTicketDialog", "Postcode", None, QtGui.QApplication.UnicodeUTF8))
        self.vehicleRegistrationLabel.setText(QtGui.QApplication.translate("newTicketDialog", "Vehicle Registration", None, QtGui.QApplication.UnicodeUTF8))
        self.newTicketTabWidget.setTabText(self.newTicketTabWidget.indexOf(self.customerTab), QtGui.QApplication.translate("newTicketDialog", "Customer", None, QtGui.QApplication.UnicodeUTF8))
        self.grossWeightLineEdit.setText(QtGui.QApplication.translate("newTicketDialog", "Gross", None, QtGui.QApplication.UnicodeUTF8))
        self.tareWeightLineEdit.setText(QtGui.QApplication.translate("newTicketDialog", "Tare", None, QtGui.QApplication.UnicodeUTF8))
        self.netWeightLineEdit.setText(QtGui.QApplication.translate("newTicketDialog", "Net", None, QtGui.QApplication.UnicodeUTF8))
        self.materialCombobox.setItemText(0, QtGui.QApplication.translate("newTicketDialog", "Copper", None, QtGui.QApplication.UnicodeUTF8))
        self.materialCombobox.setItemText(1, QtGui.QApplication.translate("newTicketDialog", "Car", None, QtGui.QApplication.UnicodeUTF8))
        self.materialCombobox.setItemText(2, QtGui.QApplication.translate("newTicketDialog", "Heavy Iron", None, QtGui.QApplication.UnicodeUTF8))
        self.payloadValueLineEdit.setText(QtGui.QApplication.translate("newTicketDialog", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.manualPriceCheckbox.setText(QtGui.QApplication.translate("newTicketDialog", "Manual price", None, QtGui.QApplication.UnicodeUTF8))
        self.addPayloadButton.setText(QtGui.QApplication.translate("newTicketDialog", "Add payload", None, QtGui.QApplication.UnicodeUTF8))
        self.totalValueLabel.setText(QtGui.QApplication.translate("newTicketDialog", "Total", None, QtGui.QApplication.UnicodeUTF8))
        self.reviewTicketButton.setText(QtGui.QApplication.translate("newTicketDialog", "Review ticket", None, QtGui.QApplication.UnicodeUTF8))
        self.newTicketTabWidget.setTabText(self.newTicketTabWidget.indexOf(self.payloadTab), QtGui.QApplication.translate("newTicketDialog", "Payload", None, QtGui.QApplication.UnicodeUTF8))

